// =============================================================================
// /catalog/: browse the curated catalog, and install from it for offline use
// -----------------------------------------------------------------------------
// The page reads catalog/catalog.json (generated by tools/catalog.mjs, the
// format in CATALOG.md) and lists every entry with what a teacher needs before
// using it: what it is and provides, how large it is, which Gravitas it works
// with, its license and how to cite it, and when and how it was reviewed.
//
// A declarative entry - a data pack or a course - installs into this browser
// (js/catalog/install.js): its archive is fetched from this origin, checked
// against the catalog's checksum and every rule the SDK writes by, validated,
// and kept in IndexedDB, so it works offline. An installed data pack opens in
// the observatory; an installed course opens here, as its units and a link
// into each lesson. A built-in entry is part of Gravitas already and has
// nothing to install.
//
// Failure is part of the design, not an afterthought: a refusal names what
// failed in the reader's language, beside the entry it belongs to, with a
// retry where one could help, and never leaves a pack half installed. Its own
// bundle, like /observatory/: nothing in the simulation imports it.
// =============================================================================

import {
  LANGUAGES,
  language,
  preferred,
  setLanguage,
  t,
  translatePage,
} from './catalog/i18n.js';
import { openStore } from './catalog/store.js';
import {
  InstallError,
  breaking,
  install,
  statusOf,
} from './catalog/install.js';
import { PLATFORM_API } from './platform/manifest.js';

const $ = id => document.getElementById(id);
const CATALOG_URL = new URL('catalog.json', document.baseURI);
const TYPES = ['all', 'data-pack', 'course-pack', 'built-in', 'installed'];

const state = {
  catalog: null,
  store: null,
  installed: new Map(),
  busy: new Set(),
  errors: new Map(),
  course: null,
};

// --- Words ---------------------------------------------------------------------------

const pick = localized =>
  localized?.[language()] ||
  localized?.en ||
  Object.values(localized || {})[0] ||
  '';

function size(bytes) {
  const kb = bytes / 1024;
  return `${new Intl.NumberFormat(language(), {
    maximumFractionDigits: kb < 10 ? 1 : 0,
  }).format(kb)} KB`;
}

function el(tag, attrs = {}, ...children) {
  const node = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs)) {
    if (k === 'text') node.textContent = v;
    else if (v !== undefined && v !== null && v !== false)
      node.setAttribute(k, v === true ? '' : String(v));
  }
  node.append(...children.filter(c => c !== null && c !== undefined));
  return node;
}

let announceTimer = null;
function status(text) {
  clearTimeout(announceTimer);
  $('catStatus').textContent = '';
  announceTimer = setTimeout(() => ($('catStatus').textContent = text), 50);
}

const typeOf = e => (e.delivery === 'built-in' ? 'built-in' : e.type);

// --- Loading ---------------------------------------------------------------------------

async function load() {
  const box = $('catLoad');
  box.replaceChildren(el('p', { class: 'cw-hint', text: t('cat.loading') }));
  try {
    const res = await fetch(CATALOG_URL, { cache: 'no-cache' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const catalog = await res.json();
    if (catalog.format !== 'gravitas.catalog' || catalog.formatVersion !== 1)
      throw new Error('not a gravitas.catalog/1');
    state.catalog = catalog;
    box.replaceChildren();
  } catch (err) {
    const retry = el('button', {
      class: 'ui-button',
      type: 'button',
      text: t('cat.retry'),
    });
    retry.addEventListener('click', () => start());
    box.replaceChildren(
      el(
        'div',
        { class: 'cw-error', role: 'alert' },
        el('p', { text: t('cat.loadFailed', { why: err.message }) }),
        retry
      )
    );
    return false;
  }
  return true;
}

async function refreshInstalled() {
  state.installed = new Map((await state.store.list()).map(r => [r.id, r]));
}

// --- The list ------------------------------------------------------------------------

function matches(e, q, type) {
  if (type === 'installed' && !state.installed.has(e.id)) return false;
  if (type !== 'all' && type !== 'installed' && typeOf(e) !== type)
    return false;
  if (!q) return true;
  const hay = [
    e.id,
    pick(e.title),
    pick(e.summary),
    e.object,
    e.facility,
    ...(e.licenses || []).map(l => l.license),
    ...(e.citations || []).map(c => c.text),
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();
  return q
    .toLowerCase()
    .split(/\s+/)
    .every(word => hay.includes(word));
}

function providesText(p) {
  const out = [];
  for (const [what, list] of Object.entries(p || {})) {
    const ids = (list || []).map(x => x.id ?? x.locale ?? x).join(', ');
    const key = `cat.provides.${what}`;
    out.push(
      ['dataPacks', 'courses', 'widgetFamilies', 'investigations'].includes(
        what
      )
        ? t(key, { ids })
        : t('cat.provides.other', { what, ids })
    );
  }
  return out.join('; ');
}

function statusText(e, s, installed) {
  const vars = {
    version: e.version,
    installed: installed?.version,
    needs: e.gravitas,
    platform: PLATFORM_API,
  };
  return t(`cat.status.${s}`, vars);
}

function entryItem(e) {
  const installed = state.installed.get(e.id) || null;
  const s = statusOf(e, installed);
  const type = typeOf(e);
  const headId = `cat-${e.id.replace(/[^A-Za-z0-9_-]/g, '-')}`;
  const meta = el('dl', { class: 'cw-meta' });
  const row = (label, value) => {
    if (!value) return;
    meta.append(el('dt', { text: label }), el('dd', {}, value));
  };
  row(
    t('cat.size'),
    e.delivery === 'archive'
      ? t('cat.size.archive', {
          download: size(e.bytes),
          unpacked: size(e.unpackedBytes),
        })
      : t('cat.size.builtIn', { bytes: size(e.bytes) })
  );
  row(t('cat.object'), e.object);
  row(
    t('cat.works'),
    t('cat.works.value', { range: e.gravitas, platform: PLATFORM_API })
  );
  row(t('cat.provides'), providesText(e.provides));
  row(t('cat.license'), (e.licenses || []).map(l => l.license).join('; '));
  if ((e.citations || []).length) {
    const list = el('ul', { class: 'cw-cites' });
    for (const c of e.citations) {
      list.append(
        el(
          'li',
          {},
          c.url
            ? el('a', { href: c.url, rel: 'noopener', text: c.text })
            : c.text
        )
      );
    }
    row(t('cat.cite'), list);
  }
  if (e.review)
    row(
      t('cat.reviewed'),
      t('cat.reviewed.value', {
        date: e.review.date,
        checks: (e.review.checks || []).join(', '),
      })
    );

  const actions = el('div', { class: 'cw-actions' });
  const busy = state.busy.has(e.id);
  const button = (text, onClick, attrs = {}) => {
    const b = el('button', {
      class: 'ui-button',
      type: 'button',
      text,
      disabled: busy,
      ...attrs,
    });
    b.addEventListener('click', onClick);
    actions.append(b);
    return b;
  };
  if (s === 'available')
    button(t('cat.install'), () => doInstall(e), { 'data-action': 'install' });
  if (s === 'update')
    button(t('cat.update', { version: e.version }), () => doInstall(e), {
      'data-action': 'update',
    });
  if (installed) {
    if (installed.type === 'data-pack')
      actions.append(
        el('a', {
          class: 'ui-button',
          href: `../observatory/?installed=${encodeURIComponent(e.id)}`,
          'data-action': 'open',
          text: t('cat.open'),
        })
      );
    if (installed.type === 'course-pack') {
      const open = state.course === e.id;
      button(
        t(open ? 'cat.hideCourse' : 'cat.showCourse'),
        () => toggleCourse(e.id),
        { 'aria-expanded': String(open), 'aria-controls': 'catCourse' }
      );
    }
    button(t('cat.remove'), () => doRemove(e), { 'data-action': 'remove' });
  }

  const notes = [];
  if (s === 'update' && installed && breaking(installed.version, e.version))
    notes.push(
      el('p', {
        class: 'cw-hint',
        text: t('cat.breaking', {
          version: e.version,
          installed: installed.version,
        }),
      })
    );
  const err = state.errors.get(e.id);
  if (err) {
    const box = el(
      'div',
      { class: 'cw-error', role: 'alert' },
      el('p', {
        text: t(`cat.error.${err.code}`, {
          check: err.check ? t(`cat.check.${err.check}`) : '',
        }),
      })
    );
    if (err.retryable || err.code === 'archive') {
      const retry = el('button', {
        class: 'ui-button',
        type: 'button',
        text: t('cat.retry'),
        disabled: busy,
      });
      retry.addEventListener('click', () => doInstall(e));
      box.append(retry);
    }
    notes.push(box);
  }

  return el(
    'li',
    {},
    el(
      'article',
      {
        class: 'cw-panel cw-entry',
        'aria-labelledby': headId,
        'data-entry': e.id,
        'data-status': s,
      },
      el('h2', { id: headId, text: pick(e.title) }),
      el(
        'p',
        { class: 'cw-badges' },
        el('span', { class: 'cw-badge', text: t(`cat.type.${type}`) }),
        el('span', {
          class: 'cw-badge',
          text: t('cat.version', { version: e.version }),
        })
      ),
      e.summary ? el('p', { text: pick(e.summary) }) : null,
      el('p', { class: 'cw-hint', text: statusText(e, s, installed) }),
      meta,
      actions,
      ...notes
    )
  );
}

function render() {
  const c = state.catalog;
  if (!c) return;
  const q = $('catSearch').value.trim();
  const type = $('catType').value || 'all';
  const shown = c.entries.filter(e => matches(e, q, type));
  $('catList').replaceChildren(...shown.map(entryItem));
  $('catCount').textContent = shown.length
    ? t('cat.count', { shown: shown.length, total: c.entries.length })
    : t('cat.none');
  $('catStorage').textContent = t(
    state.store?.persistent ? 'cat.storage.persistent' : 'cat.storage.memory'
  );
  renderCourse();
}

// --- Installing ----------------------------------------------------------------------

async function fetchBytes(url) {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}

async function doInstall(e) {
  state.busy.add(e.id);
  state.errors.delete(e.id);
  render();
  status(t('cat.installing', { title: pick(e.title) }));
  try {
    await install(e, {
      catalog: state.catalog,
      store: state.store,
      fetchBytes,
      base: CATALOG_URL,
    });
    await refreshInstalled();
    status(t('cat.installedNow', { title: pick(e.title) }));
  } catch (err) {
    const code = err instanceof InstallError ? err.code : 'content';
    state.errors.set(e.id, {
      code,
      check: err.detail?.archive,
      retryable: Boolean(err.retryable),
    });
    status(
      t(`cat.error.${code}`, {
        check: err.detail?.archive ? t(`cat.check.${err.detail.archive}`) : '',
      })
    );
  } finally {
    state.busy.delete(e.id);
    render();
  }
}

async function doRemove(e) {
  state.busy.add(e.id);
  render();
  try {
    await state.store.remove(e.id);
    await refreshInstalled();
    if (state.course === e.id) state.course = null;
    status(t('cat.removed', { title: pick(e.title) }));
  } finally {
    state.busy.delete(e.id);
    render();
  }
}

// --- An installed course -------------------------------------------------------------

function toggleCourse(id) {
  state.course = state.course === id ? null : id;
  render();
  if (state.course) $('catCourse').focus();
}

function renderCourse() {
  const box = $('catCourse');
  const record = state.course && state.installed.get(state.course);
  if (!record) {
    box.hidden = true;
    box.replaceChildren();
    return;
  }
  const file = record.manifest.provides.courses[0].file;
  const course = JSON.parse(record.files[file]);
  const lessons = state.catalog.lessons || {};
  const units = course.units.map(u =>
    el(
      'section',
      {},
      el('h3', { text: pick(u.title) }),
      el(
        'ol',
        {},
        ...u.lessons.map(l => {
          const title = pick(lessons[l.lesson]) || l.lesson;
          return el(
            'li',
            {},
            el('a', {
              href: `../#investigation=${encodeURIComponent(l.lesson)}`,
              text: t('cat.course.open', { title }),
            }),
            l.teacherNote
              ? el(
                  'p',
                  { class: 'cw-note' },
                  el('strong', { text: `${t('cat.course.teacher')}: ` }),
                  pick(l.teacherNote)
                )
              : null,
            l.studentNote
              ? el(
                  'p',
                  { class: 'cw-note' },
                  el('strong', { text: `${t('cat.course.student')}: ` }),
                  pick(l.studentNote)
                )
              : null
          );
        })
      )
    )
  );
  box.setAttribute(
    'aria-label',
    t('cat.course.label', { title: pick(course.title) })
  );
  box.replaceChildren(
    el('h2', { text: pick(course.title) }),
    el('p', { text: pick(course.summary) }),
    ...units
  );
  box.hidden = false;
}

// --- Language and start --------------------------------------------------------------

function renderLanguages() {
  $('langSwitch').replaceChildren(
    ...LANGUAGES.map(l => {
      const b = el('button', {
        type: 'button',
        class: 'ui-button',
        lang: l.id,
        text: l.endonym,
        'aria-pressed': String(language() === l.id),
      });
      b.addEventListener('click', () => {
        setLanguage(l.id);
        translateAll();
      });
      return b;
    })
  );
}

function fillTypes() {
  const sel = $('catType');
  const keep = sel.value || 'all';
  sel.replaceChildren(
    ...TYPES.map(k =>
      el('option', { value: k, text: t(`cat.filter.type.${k}`) })
    )
  );
  sel.value = keep;
}

function translateAll() {
  translatePage();
  renderLanguages();
  fillTypes();
  render();
}

$('catSearch').addEventListener('input', render);
$('catType').addEventListener('change', render);

async function start() {
  const loaded = await load();
  if (loaded) {
    state.store ??= await openStore();
    await refreshInstalled();
    render();
  }
  // Ready either way, and which: what a test or a reader's script waits on.
  document.documentElement.dataset.catalog = loaded ? 'loaded' : 'failed';
  document.documentElement.dataset.ready = 'true';
}

setLanguage(preferred());
translateAll();
start();
