// =============================================================================
// /teaching/ - the showcase page
// -----------------------------------------------------------------------------
// A static document with six live figures in it, addressed to instructors,
// prospective adopters and search committees.
//
// Three constraints shaped this file, and all three are worth stating because
// each one rules out the obvious implementation.
//
// It carries no simulation. A demonstration is a share link - the encoded form
// of a scenario, a seed and a few settings, generated by
// tools/build-teaching-demos.mjs into js/data/teachingGenerated.js - handed to
// an iframe in embed mode or opened in the application in a new tab. There is
// no second pathway into the physics here, no second copy of the share codec,
// and no canvas.
//
// It carries no numbers. Everything countable on the page is read at render
// time from the lesson manifest, from the browse metadata and from
// validation/data.json. If a lesson is added, or lengthened past the
// twenty-five-minute mark that makes it a demonstration, this page says so on
// the next load with nothing edited.
//
// It is not in the application's bundle. build.js compiles this to its own
// file, exactly as it does the instructor portal and the validation page, so
// none of it reaches a visitor who only opens the simulation. That is why the
// translator here is js/teaching/i18n.js and not js/i18n/index.js, and why
// nothing below imports the scenario catalogue, the renderer, or appState.
//
// Progressive enhancement, honestly bounded: the headings, the standing prose
// and every link out of the page are in the HTML and work with this file
// blocked. The generated sections and the figures do not, and there is no
// pretending otherwise - a page about an interactive simulator does not have a
// no-JavaScript story worth writing.
// =============================================================================

import { MANIFEST as MANIFEST_EN } from './data/investigations/manifest.js';
import { MANIFEST as MANIFEST_ES } from './data/investigations/manifest.es.js';
import { lengthOf } from './data/investigations/sequences.js';
import {
  CYCLE,
  JOURNEY,
  INSTRUMENTS,
  DEMOS,
  PATTERNS,
  EVIDENCE,
} from './data/teaching.js';
import { DEMO_LINKS, SCENARIO_COUNT } from './data/teachingGenerated.js';
import {
  LANGUAGES,
  applyTranslations,
  language,
  preferred,
  setLanguage,
  tr,
} from './teaching/i18n.js';

const $ = id => document.getElementById(id);

/** The catalogue in the language the page is being read in. */
const manifest = () => (language() === 'es' ? MANIFEST_ES : MANIFEST_EN);

/** A manifest entry by id, in the current language. */
const lessonMeta = id => manifest().find(entry => entry.id === id) ?? null;

// --- Small DOM helpers --------------------------------------------------------
// textContent throughout. Nothing on this page assembles markup from a string,
// so a stray angle bracket in a translation is a stray angle bracket and not a
// parse - the same rule js/i18n/dom.js holds the application to.

/**
 * An element with text, classes and attributes.
 * @param {string} tag - Element name
 * @param {Object} [options] - class, text, attrs, children
 * @returns {HTMLElement} The element
 */
function el(tag, { className, text, attrs, children } = {}) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  for (const [name, value] of Object.entries(attrs || {})) {
    if (value !== null && value !== undefined) node.setAttribute(name, value);
  }
  for (const child of children || []) node.append(child);
  return node;
}

/** Empty a container without leaving listeners attached to detached nodes. */
function clear(node) {
  if (node) node.replaceChildren();
}

/** Say something in the page's live region. */
function announce(message) {
  const region = $('teachLive');
  if (!region) return;
  // Cleared first: assigning the same text twice running is not a change, and
  // a screen reader says nothing. Two demonstrations opened in a row would
  // otherwise be announced once.
  region.textContent = '';
  region.textContent = message;
}

// --- The numbers --------------------------------------------------------------

/**
 * The counts the page prints, from the catalogue as it stands right now.
 * @returns {{lessons: number, steps: number, graded: number}} Totals
 */
export function catalogueTotals(entries = manifest()) {
  return entries.reduce(
    (acc, entry) => ({
      lessons: acc.lessons + 1,
      steps: acc.steps + (entry.stepCount || 0),
      graded: acc.graded + (entry.gradedCount || 0),
    }),
    { lessons: 0, steps: 0, graded: 0 }
  );
}

/** One cell of the "at a glance" strip. */
function glanceCell(key, value) {
  return el('li', {
    children: [
      el('span', { className: 'glance-key', text: tr(key) }),
      el('span', { className: 'glance-value', text: value }),
    ],
  });
}

function renderGlance() {
  const list = $('teachGlance');
  if (!list) return;
  const totals = catalogueTotals();
  clear(list);
  list.append(
    glanceCell('teach.glance.investigations', String(totals.lessons)),
    glanceCell(
      'teach.glance.graded',
      tr('teach.glance.graded.value', {
        graded: totals.graded,
        total: totals.steps,
      })
    ),
    glanceCell('teach.glance.scenarios', String(SCENARIO_COUNT)),
    glanceCell(
      'teach.glance.languages',
      LANGUAGES.map(l => l.endonym).join(', ')
    ),
    glanceCell('teach.glance.cost', tr('teach.glance.cost.value'))
  );
}

/**
 * The validation results, fetched once and reused across a language change.
 *
 * Failure is not an error state on this page. The results are a courtesy - the
 * validation page itself is one link away and always current - so a fetch that
 * does not answer leaves the cell out rather than putting an apology in it.
 */
let validationSummary = null;

async function loadValidation() {
  try {
    const res = await fetch('/validation/data.json', { cache: 'no-cache' });
    if (!res.ok) return null;
    const data = await res.json();
    const passed = Number(data.passed);
    const failed = Number(data.failed);
    if (!Number.isFinite(passed) || !Number.isFinite(failed)) return null;
    return { passed, total: passed + failed, date: String(data.generatedAt) };
  } catch {
    return null;
  }
}

function renderValidation() {
  const glance = $('teachGlance');
  const line = $('teachChecks');
  if (!validationSummary) {
    if (line) line.textContent = tr('teach.evidence.checks.unavailable');
    return;
  }
  const { passed, total, date } = validationSummary;
  if (line)
    line.textContent = tr('teach.evidence.checks', { passed, total, date });
  if (glance) {
    glance.append(
      glanceCell(
        'teach.glance.checks',
        tr('teach.glance.checks.value', { passed, total })
      )
    );
  }
}

// --- The cycle, the journey, the instruments ----------------------------------

function renderCycle() {
  const list = $('teachCycle');
  if (!list) return;
  clear(list);
  CYCLE.forEach((id, index) => {
    list.append(
      el('li', {
        className: 'teach-step',
        children: [
          el('span', {
            className: 'teach-step-n',
            text: String(index + 1),
            attrs: { 'aria-hidden': 'true' },
          }),
          el('h3', { text: tr(`teach.cycle.${id}.verb`) }),
          el('p', { text: tr(`teach.cycle.${id}.student`) }),
          el('p', {
            className: 'teach-step-tool',
            text: tr(`teach.cycle.${id}.tool`),
          }),
        ],
      })
    );
  });
}

function renderJourney() {
  const list = $('teachJourney');
  if (!list) return;
  clear(list);
  JOURNEY.forEach((id, index) => {
    list.append(
      el('li', {
        className: 'teach-stage',
        children: [
          el('span', {
            className: 'teach-stage-n',
            text: String(index + 1),
            attrs: { 'aria-hidden': 'true' },
          }),
          el('div', {
            children: [
              el('h3', { text: tr(`teach.journey.${id}.title`) }),
              el('p', { text: tr(`teach.journey.${id}.text`) }),
            ],
          }),
        ],
      })
    );
  });
}

function renderInstruments() {
  const list = $('teachInstruments');
  if (!list) return;
  clear(list);
  for (const { id, href } of INSTRUMENTS) {
    const card = el('div', {
      className: 'doc-feature teach-instrument',
      children: [
        el('h3', { text: tr(`teach.instruments.${id}.name`) }),
        el('p', { text: tr(`teach.instruments.${id}.text`) }),
      ],
    });
    if (href) {
      card.append(
        el('p', {
          children: [
            el('a', { text: tr('teach.instruments.more'), attrs: { href } }),
          ],
        })
      );
    }
    list.append(card);
  }
}

// --- The demonstrations -------------------------------------------------------

/** The fragment for a demonstration, with its '#'. */
const fragmentFor = demo => `#${DEMO_LINKS[demo.id]}`;

/**
 * Where a demonstration opens.
 *
 * Embed mode is a query parameter and the state is a fragment, which is the
 * whole reason the two compose: see the header of js/embed.js. Built here
 * rather than written into the markup because the fragment is generated.
 *
 * @param {Object} demo - An entry of DEMOS
 * @param {boolean} embedded - True for the in-page figure
 * @returns {string} A URL relative to the site root
 */
export function demoHref(demo, embedded) {
  return `/${embedded ? '?embed=1' : ''}${fragmentFor(demo)}`;
}

/** A labelled block inside a demonstration card. */
function demoField(labelId, text) {
  return el('div', {
    className: 'teach-demo-field',
    children: [el('dt', { text: tr(labelId) }), el('dd', { text })],
  });
}

/**
 * One demonstration card.
 *
 * The figure is not in the card until somebody asks for it. Six iframes each
 * booting a simulation would be six canvases, six physics loops and a
 * megabyte-and-a-half of application on a page most readers will scroll past -
 * and every one of them would start moving, which is exactly what the section
 * above it says this page does not do.
 */
function demoCard(demo) {
  const meta = lessonMeta(demo.lesson);
  const name = meta?.title ?? demo.lesson;

  const figure = el('div', {
    className: 'teach-figure',
    attrs: { hidden: '' },
  });

  const runButton = el('button', {
    className: 'ui-button is-primary',
    text: tr('teach.demo.run'),
    attrs: { type: 'button', 'aria-expanded': 'false' },
  });

  runButton.addEventListener('click', () => {
    const open = figure.hasAttribute('hidden');
    if (open) {
      const frame = el('iframe', {
        className: 'teach-frame',
        attrs: {
          src: demoHref(demo, true),
          title: tr('teach.demo.frameTitle', { name }),
          loading: 'lazy',
          allowfullscreen: '',
        },
      });
      figure.replaceChildren(frame);
      figure.removeAttribute('hidden');
      runButton.textContent = tr('teach.demo.stop');
      runButton.setAttribute('aria-expanded', 'true');
      announce(tr('teach.demo.opened', { name }));
    } else {
      // Emptied rather than hidden. An iframe left in the document keeps its
      // simulation running, its physics worker alive and its animation frames
      // scheduled, behind a display:none that hides all of it from the reader
      // but not from the machine.
      figure.replaceChildren();
      figure.setAttribute('hidden', '');
      runButton.textContent = tr('teach.demo.run');
      runButton.setAttribute('aria-expanded', 'false');
      announce(tr('teach.demo.closed', { name }));
    }
  });

  const actions = el('div', {
    className: 'teach-demo-actions',
    children: [
      runButton,
      el('a', {
        className: 'ui-button is-quiet',
        text: tr('teach.demo.open'),
        attrs: {
          href: demoHref(demo, false),
          target: '_blank',
          rel: 'noopener',
        },
      }),
      el('a', {
        className: 'ui-button is-quiet',
        text: tr('teach.demo.lesson'),
        attrs: { href: `/#investigation=${encodeURIComponent(demo.lesson)}` },
      }),
    ],
  });

  const header = el('header', {
    className: 'teach-demo-head',
    children: [el('h3', { text: name })],
  });

  // The duration, the step count and the marked count belong to the full
  // investigation, not to this demonstration - a demonstration is a paused
  // world somebody looks at for as long as the point takes to land, and it has
  // no duration to state. Under the title they read as the demonstration's
  // own, which is a figure this page has no business inventing, so they sit
  // beneath the link they describe and say whose they are.
  const investigationMeta = meta
    ? el('p', {
        className: 'teach-demo-meta',
        text: tr('teach.demo.meta', {
          duration: meta.duration,
          steps: meta.stepCount,
          graded: meta.gradedCount,
        }),
      })
    : null;

  return el('article', {
    className: 'teach-demo',
    children: [
      header,
      el('dl', {
        className: 'teach-demo-fields',
        children: [
          demoField(
            'teach.demo.question',
            tr(`teach.demo.${demo.id}.question`)
          ),
          demoField(
            'teach.demo.instructor',
            tr(`teach.demo.${demo.id}.instructor`)
          ),
          demoField('teach.demo.predict', tr(`teach.demo.${demo.id}.predict`)),
          demoField('teach.demo.visible', tr(`teach.demo.${demo.id}.visible`)),
        ],
      }),
      actions,
      ...(investigationMeta ? [investigationMeta] : []),
      figure,
    ],
  });
}

/**
 * The six links, absolute, one per line - the format Lecture Mode's textarea
 * parses. See parseSequence() in js/lecture.js.
 *
 * @returns {string} The sequence
 */
export function lectureSequence(origin = location.origin) {
  return DEMOS.map(demo => `${origin}${demoHref(demo, false)}`).join('\n');
}

function renderDemos() {
  const grid = $('teachDemos');
  if (!grid) return;
  clear(grid);
  for (const demo of DEMOS) grid.append(demoCard(demo));

  const copy = $('teachCopySequence');
  const fallback = $('teachSequenceText');
  if (!copy || !fallback) return;
  copy.textContent = tr('teach.demos.sequence');
  copy.onclick = async () => {
    const text = lectureSequence();
    try {
      await navigator.clipboard.writeText(text);
      announce(tr('teach.demos.sequence.done'));
      copy.textContent = tr('teach.demos.sequence.done');
      // Back to its own label afterwards. A button whose name is a sentence
      // about something that already happened is not a button any more, and
      // the live region above has already said it to anyone not watching.
      window.setTimeout(() => {
        copy.textContent = tr('teach.demos.sequence');
      }, 4000);
    } catch {
      // Clipboard access is refused in plenty of ordinary situations - an
      // insecure origin, a permissions policy, a browser that asks first. The
      // links are the point, so show them.
      fallback.textContent = text;
      fallback.hidden = false;
      announce(tr('teach.demos.sequence.failed'));
    }
  };
}

// --- Course patterns ----------------------------------------------------------

/**
 * The lessons that fit a slot, by the length each one declares.
 *
 * Nothing here decides that a lesson is short. lengthOf() reads the duration
 * off the manifest entry and buckets it, which is the same function the lesson
 * browser's filter uses - so this list and that filter cannot disagree, and a
 * lesson that grows past twenty-five minutes leaves the demonstration slot in
 * both places at once.
 *
 * @param {?string} fit - A bucket id, or null for a pattern that has no list
 * @returns {Array<Object>} Manifest entries
 */
export function lessonsFitting(fit, entries = manifest()) {
  if (!fit) return [];
  return entries.filter(entry => lengthOf(entry) === fit);
}

function renderPatterns() {
  const grid = $('teachPatterns');
  if (!grid) return;
  clear(grid);
  for (const pattern of PATTERNS) {
    const card = el('article', {
      className: 'teach-pattern',
      children: [
        el('h3', { text: tr(`teach.pattern.${pattern.id}.title`) }),
        el('p', { text: tr(`teach.pattern.${pattern.id}.text`) }),
        el('dl', {
          className: 'teach-pattern-meta',
          children: [
            el('dt', { text: tr('teach.patterns.prep') }),
            el('dd', { text: tr(`teach.pattern.${pattern.id}.prep`) }),
            el('dt', { text: tr('teach.patterns.handin') }),
            el('dd', { text: tr(`teach.pattern.${pattern.id}.handin`) }),
          ],
        }),
      ],
    });

    if (pattern.fit) {
      const fitting = lessonsFitting(pattern.fit);
      const list = el('ul', { className: 'teach-fitting' });
      for (const entry of fitting) {
        list.append(
          el('li', {
            children: [
              el('a', {
                text: entry.title,
                attrs: {
                  href: `/#investigation=${encodeURIComponent(entry.id)}`,
                },
              }),
              el('span', {
                className: 'teach-fitting-time',
                text: entry.duration,
              }),
            ],
          })
        );
      }
      card.append(
        el('h4', {
          className: 'teach-fitting-head',
          text: tr('teach.patterns.fits'),
        })
      );
      card.append(
        fitting.length ? list : el('p', { text: tr('teach.patterns.none') })
      );
    }

    grid.append(card);
  }
}

// --- Evidence -----------------------------------------------------------------

function renderEvidence() {
  const grid = $('teachEvidence');
  if (!grid) return;
  clear(grid);
  for (const { id, href } of EVIDENCE) {
    const external = /^https?:/.test(href);
    grid.append(
      el('article', {
        className: 'teach-evidence',
        children: [
          el('h3', {
            children: [
              el('a', {
                text: tr(`teach.evidence.${id}.name`),
                attrs: {
                  href,
                  rel: external ? 'noopener' : null,
                  target: external ? '_blank' : null,
                },
              }),
            ],
          }),
          el('p', { text: tr(`teach.evidence.${id}.text`) }),
        ],
      })
    );
  }
}

// --- The language switch ------------------------------------------------------

function renderLanguageSwitch() {
  const group = $('teachLang');
  if (!group) return;
  clear(group);
  for (const lang of LANGUAGES) {
    const active = lang.id === language();
    const button = el('button', {
      className: 'ui-button is-quiet',
      text: lang.endonym,
      attrs: {
        type: 'button',
        lang: lang.id,
        'aria-pressed': String(active),
      },
    });
    button.addEventListener('click', () => {
      if (lang.id === language()) return;
      setLanguage(lang.id);
      renderAll();
      announce(tr('teach.lang.switched'));
    });
    group.append(button);
  }
}

// --- Assembly -----------------------------------------------------------------

/**
 * Draw the whole page.
 *
 * Called again, in full, on a language change. Re-rendering everything is
 * cheaper to reason about than a partial update, and it is what guarantees the
 * lesson titles, the durations and the slot lists change language along with
 * the prose: they come out of a different manifest, not out of a catalogue.
 *
 * One thing it deliberately does not preserve: an open figure. A reader who
 * switches language while a demonstration is running gets it closed rather
 * than reloaded, because reloading it would restart the simulation they were
 * halfway through and silently discard where it had got to.
 */
function renderAll() {
  document.documentElement.setAttribute('lang', language());
  applyTranslations();
  // The <meta> description is what a link preview and a search result show, and
  // a reader who has chosen Spanish should get a Spanish one. Set here rather
  // than swept, because a meta element has no text node to translate.
  const description = document.querySelector('meta[name="description"]');
  if (description)
    description.setAttribute('content', tr('teach.meta.description'));
  renderLanguageSwitch();
  renderGlance();
  renderValidation();
  renderCycle();
  renderJourney();
  renderInstruments();
  renderDemos();
  renderPatterns();
  renderEvidence();
}

/** Wire the page up. */
export async function initTeachingPage() {
  setLanguage(preferred());
  renderAll();
  // After the first paint. The results are one number in a strip of five and
  // one line at the bottom; nothing above them should wait on a fetch.
  validationSummary = await loadValidation();
  renderGlance();
  renderValidation();
}
