import js from '@eslint/js';
import prettier from 'eslint-plugin-prettier';
import prettierConfig from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  {
    // Node build tooling. Mostly not browser code, with one exception: the
    // thumbnail generator's page.evaluate() callbacks are serialized and run
    // inside headless Chromium, so this file legitimately contains both halves
    // and needs both sets of globals.
    files: ['build.js', 'tools/*.js', 'tools/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        URL: 'readonly',
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        getComputedStyle: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
      },
    },
    plugins: { prettier },
    rules: {
      ...prettierConfig.rules,
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'prettier/prettier': 'error',
    },
  },
  {
    // Web Workers run in a different global scope than the page modules
    files: ['js/physicsWorker.js', 'js/chartWorker.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
      globals: {
        self: 'readonly',
        postMessage: 'readonly',
        performance: 'readonly',
        Math: 'readonly',
        Float32Array: 'readonly',
        Int32Array: 'readonly',
        Array: 'readonly',
        console: 'readonly',
      },
    },
    plugins: { prettier },
    rules: {
      ...prettierConfig.rules,
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'prettier/prettier': 'error',
    },
  },
  {
    files: ['js/**/*.js'],
    ignores: ['js/physicsWorker.js', 'js/chartWorker.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        canvas: 'readonly',
        ctx: 'readonly',
        starfieldCanvas: 'readonly',
        starfieldCtx: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        location: 'readonly',
        history: 'readonly',
        crypto: 'readonly',
        // Used by the shared-link codec in shareState.js
        btoa: 'readonly',
        atob: 'readonly',
        Blob: 'readonly',
        Response: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        CompressionStream: 'readonly',
        DecompressionStream: 'readonly',
        performance: 'readonly',
        navigator: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        Image: 'readonly',
        HTMLCanvasElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        MouseEvent: 'readonly',
        TouchEvent: 'readonly',
        KeyboardEvent: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        Math: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        JSON: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        Date: 'readonly',
        RegExp: 'readonly',
        Error: 'readonly',
        Promise: 'readonly',
        Set: 'readonly',
        Map: 'readonly',
        WeakSet: 'readonly',
        WeakMap: 'readonly',
        Symbol: 'readonly',
        Proxy: 'readonly',
        Reflect: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        decodeURI: 'readonly',
        decodeURIComponent: 'readonly',
        encodeURI: 'readonly',
        encodeURIComponent: 'readonly',
        Worker: 'readonly',
        Blob: 'readonly',
        MutationObserver: 'readonly',
        CustomEvent: 'readonly',
        Chart: 'readonly',
        Float32Array: 'readonly',
        Int32Array: 'readonly',
        ArrayBuffer: 'readonly',
        OffscreenCanvas: 'readonly',
        matchMedia: 'readonly',
        getComputedStyle: 'readonly',
        CSS: 'readonly',
        Int8Array: 'readonly',
        Float64Array: 'readonly',
        PointerEvent: 'readonly',
        CustomEvent: 'readonly',
      },
    },
    plugins: {
      prettier,
    },
    rules: {
      ...prettierConfig.rules,
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'prettier/prettier': 'error',
    },
  },
];
