// =============================================================================
// Gravitas service worker
// -----------------------------------------------------------------------------
// The problem this exists for is specific: a class is twenty minutes into a
// lesson, the school wifi drops, and the simulation stops being a simulation
// and becomes a broken tab. Nothing here is about making the first load faster.
// It is about the second half of a lesson surviving the network.
//
// The precache list and the cache name are generated by
// tools/build-service-worker.mjs and live in sw-manifest.js. The name is a hash
// of the contents of every precached file, which is what makes the cache safe
// both ways: a rebuild that changed nothing keeps the cache a returning browser
// already has, and a rebuild that changed one byte of one module produces a new
// name, so the old one is deleted on activate and nothing stale can survive.
//
// Three strategies, and the reason for each
// -----------------------------------------------------------------------------
//   navigations        network first, falling back to the cached shell. A
//                      teacher who reloads on a working network must get the
//                      current build; a teacher who reloads on a dead one must
//                      still get the application.
//   precached assets   cache first. They are versioned by the cache name, so a
//                      hit is known-current and there is no reason to ask the
//                      network. This is what makes the offline case instant
//                      rather than merely possible.
//   everything else    stale-while-revalidate. The Spanish lesson shadows, the
//                      document pages, anything added later: served from cache
//                      when there is one, refreshed in the background.
//
// What it deliberately does not do
// -----------------------------------------------------------------------------
// It does not call skipWaiting() on install. Replacing the running code while a
// class is mid-lesson is exactly the kind of surprise this is supposed to
// prevent - a new worker waits, and takes over on the next load. The page can
// ask for an immediate swap by posting 'skip-waiting', and nothing in the
// application does that unprompted.
//
// It does not cache anything but same-origin GETs. No opaque responses, no
// range requests, nothing partial.
// =============================================================================

importScripts('./sw-manifest.js');

const VERSION = self.__GRAVITAS_CACHE_VERSION || 'gravitas-dev';
const PRECACHE = self.__GRAVITAS_PRECACHE || [];
const LOCALE_WARM = self.__GRAVITAS_LOCALE_WARM || {};

/**
 * Add a list of URLs to the cache, tolerating individual failures.
 *
 * cache.addAll() is atomic: one 404 anywhere in a 188-file list and nothing is
 * cached at all. For an offline classroom that trade is the wrong way round -
 * 187 files cached and one missing beats a browser with no offline copy because
 * a thumbnail was renamed. Failures are counted and reported rather than
 * swallowed, so a broken manifest is still visible to anyone who looks.
 *
 * @param {Cache} cache - The open cache
 * @param {string[]} urls - What to fetch
 * @returns {Promise<{added: number, failed: string[]}>} What happened
 */
async function addAllTolerant(cache, urls) {
  let added = 0;
  const failed = [];
  // Batched rather than all at once: 188 parallel requests on a school
  // connection is how a browser starts cancelling them.
  const BATCH = 12;
  for (let i = 0; i < urls.length; i += BATCH) {
    const slice = urls.slice(i, i + BATCH);
    await Promise.all(
      slice.map(async url => {
        try {
          // reload: bypass the HTTP cache for the install itself, so a new
          // version is genuinely fetched rather than re-copied from a stale
          // browser cache entry.
          const response = await fetch(new Request(url, { cache: 'reload' }));
          if (!response.ok) throw new Error(String(response.status));
          await cache.put(url, response);
          added++;
        } catch (err) {
          failed.push(`${url}: ${err.message}`);
        }
      })
    );
  }
  return { added, failed };
}

self.addEventListener('install', event => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(VERSION);
      const { added, failed } = await addAllTolerant(cache, PRECACHE);
      if (failed.length) {
        console.warn(
          `[gravitas-sw] ${failed.length} of ${PRECACHE.length} precache entries failed:`,
          failed.slice(0, 10)
        );
      }
      console.info(
        `[gravitas-sw] installed ${VERSION}: ${added}/${PRECACHE.length} files cached.`
      );
      // No skipWaiting. See the header.
    })()
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter(name => name.startsWith('gravitas-') && name !== VERSION)
          .map(name => caches.delete(name))
      );
      await clients.claim();
      console.info(`[gravitas-sw] active: ${VERSION}`);
    })()
  );
});

/**
 * Whether a request is one this worker will answer at all.
 *
 * @param {Request} request - The request
 * @returns {boolean} True for a plain same-origin GET
 */
function handleable(request) {
  if (request.method !== 'GET') return false;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return false;
  // A range request wants part of a body; a cached whole one is the wrong
  // answer and Safari in particular will not forgive it.
  if (request.headers.has('range')) return false;
  return true;
}

/**
 * Look a request up in the cache, tolerating a cache-busting query string.
 *
 * index.html asks for the stylesheets as `css/styles.css?v=3`, while the
 * precache stores them under the path the generator walked. cache.match() is
 * exact by default, query string included, so the precached copy was invisible
 * to the request that wanted it and the application booted offline with no CSS
 * at all - readable, arguably, and not something to ship.
 *
 * Exact first, so a genuinely distinct query still gets its own entry, then
 * ignoreSearch. In this application a query string is only ever a cache
 * buster: nothing serves different content for the same path.
 *
 * @param {Cache} cache - The open cache
 * @param {Request} request - What was asked for
 * @returns {Promise<?Response>} The cached response, or undefined
 */
async function matchCached(cache, request) {
  return (
    (await cache.match(request)) ||
    (await cache.match(request, { ignoreSearch: true }))
  );
}

/**
 * Cache a response if it is worth caching.
 *
 * @param {Cache} cache - The open cache
 * @param {Request} request - What was asked for
 * @param {Response} response - What came back
 * @returns {Response} The same response, for chaining
 */
function maybeCache(cache, request, response) {
  if (response && response.ok && response.type === 'basic') {
    cache.put(request, response.clone()).catch(() => {
      /* quota, or a concurrent delete during activate; neither is fatal */
    });
  }
  return response;
}

self.addEventListener('fetch', event => {
  const { request } = event;
  if (!handleable(request)) return;

  // Navigations: network first, cached shell as the fallback.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        const cache = await caches.open(VERSION);
        try {
          const fresh = await fetch(request);
          return maybeCache(cache, request, fresh);
        } catch {
          return (
            (await matchCached(cache, request)) ||
            (await cache.match('./index.html')) ||
            (await cache.match('index.html')) ||
            Response.error()
          );
        }
      })()
    );
    return;
  }

  event.respondWith(
    (async () => {
      const cache = await caches.open(VERSION);
      const hit = await matchCached(cache, request);

      if (hit) {
        // A precached file is current by construction - the cache name is a
        // hash of its contents - so there is nothing to revalidate. Anything
        // else gets refreshed in the background while the hit is served.
        const url = new URL(request.url);
        const relative = `.${url.pathname}`;
        // Compared on the path alone, for the same reason matchCached ignores
        // the search: `css/styles.css?v=3` is the precached `css/styles.css`.
        if (!PRECACHE.includes(relative)) {
          event.waitUntil(
            fetch(request)
              .then(fresh => maybeCache(cache, request, fresh))
              .catch(() => {
                /* offline: the hit we already served is the right answer */
              })
          );
        }
        return hit;
      }

      try {
        return maybeCache(cache, request, await fetch(request));
      } catch {
        // Nothing cached and no network. Let the application see a failure it
        // can report rather than a hang.
        return new Response(`Offline and not cached: ${request.url}`, {
          status: 504,
          statusText: 'Offline',
          headers: { 'content-type': 'text/plain' },
        });
      }
    })()
  );
});

self.addEventListener('message', event => {
  const data = event.data || {};

  if (data.type === 'skip-waiting') {
    self.skipWaiting();
    return;
  }

  // Warm a locale's lesson shadows. The twelve Spanish files are not precached
  // - they are 439KB that most readers never fetch - so the page asks for them
  // when the interface switches to Spanish, which is the moment they stop being
  // hypothetical.
  if (data.type === 'warm-locale') {
    const urls = LOCALE_WARM[data.locale];
    if (!urls || !urls.length) return;
    event.waitUntil(
      (async () => {
        const cache = await caches.open(VERSION);
        const { added, failed } = await addAllTolerant(cache, urls);
        console.info(
          `[gravitas-sw] warmed ${data.locale}: ${added}/${urls.length}` +
            (failed.length ? `, ${failed.length} failed` : '')
        );
      })()
    );
    return;
  }

  // A status reply, for the diagnostics readout and for the tests, which need
  // to know what is actually cached rather than guess from timing.
  if (data.type === 'status' && event.ports && event.ports[0]) {
    const port = event.ports[0];
    (async () => {
      const cache = await caches.open(VERSION);
      const keys = await cache.keys();
      port.postMessage({
        version: VERSION,
        precacheCount: PRECACHE.length,
        precacheBytes: self.__GRAVITAS_PRECACHE_BYTES || 0,
        cachedCount: keys.length,
      });
    })();
  }
});
