// One experiment format (Roadmap II, Prompt 66, step 4). The bench writes
// gravitas.experiment/1 and gravitas.experiment-result/1; the runner opens a
// comparison; the two retired ids stay readable as version 0.
//
// The fixtures are not hand-made. tests/fixtures/experiment-formats/ holds
// what the code on main (16d0f24: store version 2) and on v2 (2617570: store
// version 3) actually wrote, generated by running that commit's own store.js
// and exports.js over one record. No commit ever wrote store version 1 (the
// bench's first commit already wrote 2), so version 1 is the shape the
// existing store tests document, not a recorded file.

import { readFileSync } from 'node:fs';
import { valid } from './jsonSchemaSubset.js';
import {
  experimentManifest,
  experimentManifestJson,
  importManifest,
  reliabilityJson,
} from '../js/experiments/exports.js';
import {
  KEY_PREFIX,
  loadExperiment,
  migrate,
  saveExperiment,
  setBackend,
} from '../js/experiments/store.js';
import {
  FORMAT,
  RESULT_FORMAT,
  RETIRED_FORMATS,
  TO_VERSION_1,
  migrateExperiment,
  reproducibility,
  underCurrentId,
  validateExperiment,
} from '../js/experiments/experimentManifest.js';

const dir = new URL('./fixtures/experiment-formats/', import.meta.url);
const fixture = name => JSON.parse(readFileSync(new URL(name, dir), 'utf8'));
const ERAS = [
  ['main', 'main-16d0f24', 2],
  ['v2', 'v2-2617570', 3],
];

describe.each(ERAS)('what %s wrote', (_era, tag, storeV) => {
  test('the manifest opens, under the retired id', () => {
    const old = fixture(`${tag}-manifest.json`);
    expect(old.format).toBe('gravitas-experiment');
    const r = importManifest(JSON.stringify(old));
    expect(r.ok).toBe(true);
    expect(r.experiment.name).toBe('Planet a doubled');
    expect(r.experiment.provenance.seed).toBe('2a');
    expect(r.experiment.diff.variables[0]).toMatchObject({
      key: 'binary_lab_planet_a',
    });
  });

  test('the old manifest and a new export of the same record import alike', () => {
    const old = importManifest(JSON.stringify(fixture(`${tag}-manifest.json`)));
    const stored = fixture(`${tag}-store-v${storeV}.json`);
    const now = importManifest(
      experimentManifestJson(migrate(stored).record, {
        appVersion: '2026.09.3',
      })
    );
    expect(now.ok).toBe(true);
    const strip = ({ created: _c, ...e }) => e;
    expect(strip(now.experiment)).toEqual(strip(old.experiment));
  });

  test('the store record migrates to the current record', () => {
    const old = fixture(`${tag}-store-v${storeV}.json`);
    expect(old.v).toBe(storeV);
    expect(old.format).toBeUndefined();
    const { ok, record } = migrate(old);
    expect(ok).toBe(true);
    expect(record).toMatchObject({
      format: RESULT_FORMAT,
      formatVersion: 1,
      kind: 'comparison',
      v: 3,
      name: 'Planet a doubled',
    });
    expect(record.runs.A.samples).toHaveLength(2);
    if (storeV < 3) {
      // Version 3 withdrew the drifts version 2 recorded as totals times 100.
      expect(record.runs.A.driftWithdrawn).toBe(true);
      expect(record.runs.A.samples[1]).not.toHaveProperty('energy_drift');
    }
  });

  test('a migrated record saves, loads and migrates to itself', () => {
    const mem = new Map();
    setBackend({
      getItem: k => mem.get(k) ?? null,
      setItem: (k, v) => mem.set(k, v),
      removeItem: k => mem.delete(k),
    });
    const { record } = migrate(fixture(`${tag}-store-v${storeV}.json`));
    expect(saveExperiment(record).ok).toBe(true);
    const raw = JSON.parse(mem.get(`${KEY_PREFIX}${record.id}`));
    expect(raw).toMatchObject({
      format: RESULT_FORMAT,
      formatVersion: 1,
      v: 3,
    });
    const back = loadExperiment(record.id);
    expect(back.ok).toBe(true);
    const { updated: _u, ...a } = back.record;
    const { updated: _w, ...b } = record;
    expect(a).toEqual(b);
    setBackend(null);
  });

  test('the retired reliability check is version 0 of the result format', () => {
    const old = fixture(`${tag}-reliability.json`);
    expect(old.kind).toBe('gravitas-reliability-check');
    const v0 = underCurrentId(old);
    expect(v0).toMatchObject({ format: RESULT_FORMAT, formatVersion: 0 });
    const doc = TO_VERSION_1[0](v0);
    expect({ doc }).toMatchObject({
      doc: {
        format: RESULT_FORMAT,
        formatVersion: 1,
        kind: 'reliability-check',
        verdict: old.verdict,
        conclusions: old.conclusions,
      },
    });
    expect(doc.version).toBeUndefined();
  });

  test('the runner opens the old comparison as a sweep', () => {
    const { manifest, notes, error } = migrateExperiment(
      fixture(`${tag}-manifest.json`)
    );
    expect(error).toBeNull();
    expect(validateExperiment(manifest)).toEqual([]);
    expect(manifest).toMatchObject({
      format: FORMAT,
      title: 'Planet a doubled',
      model: { scenario: 'Binary Planet Lab' },
      vary: [{ parameter: 'binary_lab_planet_a', values: [0.1, 0.2] }],
      stop: { duration: 125 },
    });
    expect(notes.join()).toMatch(/two values of binary_lab_planet_a/);
  });
});

describe('what this build writes', () => {
  const record = migrate(fixture('v2-2617570-store-v3.json')).record;

  test('the manifest is gravitas.experiment/1 and round-trips', () => {
    const m = experimentManifest(record, { appVersion: 'x' });
    expect(m).toMatchObject({
      format: 'gravitas.experiment',
      formatVersion: 1,
      kind: 'comparison',
    });
    expect(m.version).toBeUndefined();
    const r = importManifest(JSON.stringify(m));
    expect(r.ok).toBe(true);
    expect(migrateExperiment(m).error).toBeNull();
  });

  test('the reliability check is a result of kind reliability-check', () => {
    const doc = JSON.parse(reliabilityJson(record, { appVersion: 'x' }));
    expect(doc).toMatchObject({
      format: RESULT_FORMAT,
      formatVersion: 1,
      kind: 'reliability-check',
    });
    expect(underCurrentId(doc)).toBe(doc);
  });

  test('a sweep manifest is not a bench comparison, and a newer one is refused', () => {
    const sweep = migrateExperiment(
      fixture('v2-2617570-manifest.json')
    ).manifest;
    expect(importManifest(JSON.stringify(sweep)).reason).toBe(
      'not-an-experiment'
    );
    const newer = { ...experimentManifest(record), formatVersion: 2 };
    expect(importManifest(JSON.stringify(newer)).reason).toBe(
      'from-a-newer-version'
    );
    expect(migrateExperiment(newer).error).toMatch(/newer than this Gravitas/);
    expect(
      importManifest(
        JSON.stringify({ format: 'gravitas-experiment', version: 2 })
      ).reason
    ).toBe('from-a-newer-version');
  });

  test('a store record from a newer version is refused, as before', () => {
    expect(migrate({ v: 4, id: 'x' }).reason).toBe('from-a-newer-version');
    expect(
      migrate({ format: RESULT_FORMAT, formatVersion: 2, id: 'x' }).reason
    ).toBe('from-a-newer-version');
    expect(migrate(null).reason).toBe('not-an-experiment');
  });

  test('a comparison the runner cannot sweep says why', () => {
    const base = fixture('v2-2617570-manifest.json');
    const two = {
      ...base,
      parameterChange: {
        variables: [
          { key: 'binary_lab_planet_a', from: 1, to: 2 },
          { key: 'gravitational_constant', from: 1, to: 2 },
        ],
      },
    };
    expect(migrateExperiment(two).error).toMatch(/changed 2 settings/);
    const other = {
      ...base,
      parameterChange: {
        variables: [{ key: 'gravitational_constant', from: 1, to: 2 }],
      },
    };
    expect(migrateExperiment(other).error).toMatch(/not a setting the runner/);
    const nowhere = {
      ...base,
      provenance: { ...base.provenance, scenario: 'Solar System' },
    };
    expect(migrateExperiment(nowhere).error).toMatch(/cannot sweep/);
  });

  test('the retired ids are exactly the two aliases', () => {
    expect(RETIRED_FORMATS).toEqual({
      'gravitas-experiment': 'gravitas.experiment',
      'gravitas-reliability-check': 'gravitas.experiment-result',
    });
  });
});

describe('the published schemas hold what the bench writes', () => {
  const schema = n =>
    JSON.parse(
      readFileSync(new URL(`../sdk/schemas/${n}.schema.json`, import.meta.url))
    );
  const record = migrate(fixture('v2-2617570-store-v3.json')).record;

  test('experiment-1 holds the manifest, and result-1 the record and the check', () => {
    const manifest = experimentManifest(record, { appVersion: 'x' });
    expect(valid(schema('experiment-1'), manifest)).toBe(true);
    expect(valid(schema('experiment-result-1'), record)).toBe(true);
    const check = JSON.parse(reliabilityJson(record, { appVersion: 'x' }));
    expect(valid(schema('experiment-result-1'), check)).toBe(true);
  });

  test('and refuses a comparison that lost what makes it one', () => {
    const manifest = experimentManifest(record, { appVersion: 'x' });
    delete manifest.parameterChange;
    expect(valid(schema('experiment-1'), manifest)).toBe(false);
    const stored = { ...record };
    delete stored.runs;
    expect(valid(schema('experiment-result-1'), stored)).toBe(false);
  });
});

describe('analysis documents and reproducibility (step 5)', () => {
  const doc = {
    format: 'gravitas.analysis',
    engine: { fingerprint: 'aaaa0000' },
    consumed: [{ kind: 'experiment-result', id: 'h1', digest: 'd1' }],
  };
  test('one sentence for an engine mismatch, in results and analyses alike', () => {
    const a = reproducibility(doc, { engine: 'bbbb1111' }).reasons[0];
    const b = reproducibility(
      {
        format: RESULT_FORMAT,
        formatVersion: 1,
        engine: { fingerprint: 'aaaa0000' },
        manifest: {},
        hash: 'x',
      },
      { engine: 'bbbb1111', app: 'x' }
    ).reasons.find(r => /integrates differently/.test(r));
    expect(a).toBe(b);
  });
  test('a changed digest is named; a matching one reproduces', () => {
    const here = { engine: 'aaaa0000', digests: { h1: 'd2' } };
    expect(reproducibility(doc, here).reasons.join()).toMatch(
      /digest d1 then, d2/
    );
    expect(
      reproducibility(doc, { engine: 'aaaa0000', digests: { h1: 'd1' } })
        .reproducible
    ).toBe(true);
  });
});

describe('review fixes', () => {
  test('a stray kind does not reclassify a retired manifest', () => {
    const d = { format: 'gravitas-experiment', version: 1, kind: 'x' };
    expect(underCurrentId(d).format).toBe('gravitas.experiment');
  });
  test('a comparison or check is not a sweep result', () => {
    for (const kind of ['comparison', 'reliability-check']) {
      const r = reproducibility(
        { format: RESULT_FORMAT, formatVersion: 1, kind },
        { engine: 'a' }
      );
      expect(r.reasons).toEqual(['not a sweep result']);
    }
  });
  test('an analysis without an engine, or without digests, is not reproducible', () => {
    const a = {
      format: 'gravitas.analysis',
      consumed: [{ id: 'h', digest: 'd' }],
    };
    expect(reproducibility(a, { engine: 'a' }).reasons.join()).toMatch(
      /not recorded/
    );
    const b = { ...a, engine: { fingerprint: 'a' } };
    expect(reproducibility(b, { engine: 'a' }).reproducible).toBe(false);
  });
  test('a comparison that changed nothing, and its dropped parts, are reported', () => {
    const m = fixture('v2-2617570-manifest.json');
    const same = {
      ...m,
      parameterChange: {
        variables: [{ key: 'binary_lab_planet_a', from: 1, to: 1 }],
      },
    };
    expect(migrateExperiment(same).error).toMatch(/did not change/);
  });
});
