// =============================================================================
// What the screen says about GW150914 is what the file says
// -----------------------------------------------------------------------------
// js/data/gw/gw150914.js is generated by tools/build-gw-data.mjs from the traces
// GWOSC published, and it carries a PROVENANCE block recording exactly what was
// done to them and exactly what was not. The prose beside the plot is written by
// hand, in two languages, and quotes several of the same facts: the band the
// collaboration filtered to, the GPS epoch the time axis is measured from, and
// the claim that nothing further has been done here.
//
// Those are two copies of one fact, which is the arrangement that goes stale.
// If the pipeline ever starts filtering, resampling differently or aligning the
// detectors, the generated metadata changes and the prose does not - and a
// teaching application that shows "LIGO data" while describing processing it no
// longer does is making a false claim about a measurement.
//
// So the numbers in the copy are checked against the module, rather than
// against a second hand-written list.
// =============================================================================

import { describe, test, expect } from '@jest/globals';
import { PROVENANCE, TRACES } from '../js/data/gw/gw150914.js';
import { EN_DEFERRED } from '../js/i18n/en.deferred.js';
import { ES_DEFERRED } from '../js/i18n/es.deferred.js';

/** The band the publisher filtered to, read out of the provenance record. */
function publishedBand() {
  const line = PROVENANCE.priorProcessingByPublisher.find(s =>
    /band-pass/i.test(s)
  );
  expect(line).toBeTruthy();
  const numbers = line.match(/\d+/g)?.map(Number) ?? [];
  expect(numbers).toHaveLength(2);
  return { low: Math.min(...numbers), high: Math.max(...numbers) };
}

/** Every string in a catalog, flattened. */
const strings = catalog =>
  Object.entries(catalog).filter(([, v]) => typeof v === 'string');

const CATALOGS = [
  ['en', EN_DEFERRED],
  ['es', ES_DEFERRED],
];

describe('the provenance record itself', () => {
  test('says what was done and what was not', () => {
    expect(Array.isArray(PROVENANCE.processing)).toBe(true);
    expect(PROVENANCE.processing.length).toBeGreaterThan(0);
    expect(Array.isArray(PROVENANCE.notApplied)).toBe(true);
    expect(Array.isArray(PROVENANCE.priorProcessingByPublisher)).toBe(true);
  });

  // The claim the copy leans on hardest: the application does not filter.
  test('records that no further filtering or whitening is applied here', () => {
    const notApplied = PROVENANCE.notApplied.join(' ').toLowerCase();
    expect(notApplied).toMatch(/filtering/);
    expect(notApplied).toMatch(/whitening/);
    expect(notApplied).toMatch(/no /);
  });

  test('the strain traces are decimated from the published rate, not resampled', () => {
    expect(PROVENANCE.sourceSampleRate).toBe(16384);
    for (const [id, trace] of Object.entries(TRACES)) {
      expect(typeof trace.sampleRate).toBe('number');
      expect(PROVENANCE.sourceSampleRate % trace.sampleRate).toBe(0);
      expect({ id, decimation: typeof trace.decimation }).toEqual({
        id,
        decimation: 'string',
      });
    }
  });
});

describe.each(CATALOGS)('the %s copy agrees with it', (lang, catalog) => {
  // Found by the shape of the claim rather than by an English phrase: the
  // Spanish copy says "filtro en banda de 35 a 350 Hz", so a search for
  // "band-pass" finds nothing there and a test that only looked for the English
  // would pass by finding nothing to check.
  test('quotes the publisher band the provenance records', () => {
    const { low, high } = publishedBand();
    const anyBand = /(\d+)\s*(?:[–-]|a)\s*(\d+)\s*Hz/;
    const quoting = strings(catalog).filter(([, v]) => anyBand.test(v));
    expect(quoting.length).toBeGreaterThan(0);
    for (const [key, value] of quoting) {
      const [, a, b] = anyBand.exec(value);
      expect({ key, low: Number(a), high: Number(b) }).toEqual({
        key,
        low,
        high,
      });
    }
  });

  test('quotes the GPS epoch the time axis is measured from', () => {
    const quoting = strings(catalog).filter(([, v]) => /GPS\s*\d/.test(v));
    expect(quoting.length).toBeGreaterThan(0);
    for (const [key, value] of quoting) {
      expect({ key, epoch: value.match(/GPS\s*(\d+)/)?.[1] }).toEqual({
        key,
        epoch: String(PROVENANCE.gpsEpoch),
      });
    }
  });

  // The failure this is really guarding: copy that credits the application with
  // processing the pipeline does not do. "The collaboration band-passed it" is
  // fine and true; "we whiten it" would not be.
  test('never claims this application filters or whitens the data', () => {
    const claimed = strings(catalog).filter(([, value]) => {
      const v = value.toLowerCase();
      if (!/whiten|filter|smooth/.test(v)) return false;
      // Anything that attributes the processing to the publisher, or denies it
      // outright, is describing the record correctly.
      if (
        /collaboration|published|publication|publisher|colaboraci|publicad/.test(
          v
        )
      )
        return false;
      if (/\bno\b|\bnothing\b|\bnada\b|\bningun/.test(v)) return false;
      return /\bwe\b|applied here|aquí|aqui/.test(v);
    });
    expect(claimed.map(([k]) => k)).toEqual([]);
  });
});
