// =============================================================================
// Can you read the instrument?
// -----------------------------------------------------------------------------
// Every lesson instrument draws its numbers onto a canvas, and a canvas has no
// cascade, no rem and no user font size: every label in it is a magic number
// in a draw function. Those numbers had drifted down to eight and nine pixels
// - about four pixels of x-height - on exactly the labels a reader has to take
// a measurement off. Nobody notices, because the person writing the widget is
// looking at it from eighteen inches away on a retina display.
//
// This is the check that keeps them up. It patches the 2D context so that every
// piece of text a panel draws is recorded with its font, its box and where it
// landed, repaints the panel, and then asks three questions of the result:
//
//   1. is anything smaller than the shared minimum in js/widgetCanvas.js
//   2. is anything drawn outside the canvas, where it is simply gone
//   3. is any label sitting on top of another one
//
// The third is the one that raising type breaks, and it is why the two go
// together: bigger labels on the same axis collide, and the answer is fewer
// labels rather than smaller ones.
//
// One panel per registered widget, from the step in the catalogue that opens
// it. The list is generated by `npm run audit:scene -- --json`, and a widget
// that no lesson opens is not tested here because a reader cannot reach it.
//
// What it does not check
// -----------------------------------------------------------------------------
// Contrast, which lives in e2e/accessibility.spec.js, and whether the label
// says anything useful, which no test can decide.
// =============================================================================

import { test, expect } from './fixtures.js';
import { TYPE } from '../js/widgetCanvas.js';

/** One step per widget, from the scene catalogue. */
const PANELS = [
  { widget: 'depth-size', lesson: 'transit-photometry', step: 6 },
  { widget: 'geometry', lesson: 'transit-photometry', step: 13 },
  { widget: 'spectrum', lesson: 'transit-photometry', step: 21 },
  { widget: 'dilution', lesson: 'transit-photometry', step: 24 },
  { widget: 'resolve', lesson: 'transit-photometry', step: 25 },
  { widget: 'launch', lesson: 'orbital-energy', step: 3 },
  { widget: 'live-energy', lesson: 'orbital-energy', step: 12 },
  { widget: 'escape-compare', lesson: 'orbital-energy', step: 17 },
  { widget: 'shapes', lesson: 'orbital-energy', step: 20 },
  { widget: 'binary', lesson: 'weighing-stars', step: 9 },
  { widget: 'balance', lesson: 'weighing-stars', step: 11 },
  { widget: 'binary-compare', lesson: 'weighing-stars', step: 17 },
  { widget: 'visual-binary', lesson: 'weighing-stars', step: 31 },
  { widget: 'bh-horizon', lesson: 'black-holes', step: 3 },
  { widget: 'bh-scaling', lesson: 'black-holes', step: 6 },
  { widget: 'bh-escape', lesson: 'black-holes', step: 11 },
  { widget: 'bh-density', lesson: 'black-holes', step: 15 },
  { widget: 'bh-blocks', lesson: 'black-holes', step: 17 },
  { widget: 'bh-thermo', lesson: 'black-holes', step: 20 },
  { widget: 'bh-lifetime', lesson: 'black-holes', step: 23 },
  { widget: 'bh-lineup', lesson: 'black-holes', step: 25 },
  { widget: 'reflex-motion', lesson: 'radial-velocity', step: 4 },
  { widget: 'rv-observer', lesson: 'radial-velocity', step: 9 },
  { widget: 'rv-mass', lesson: 'radial-velocity', step: 16 },
  { widget: 'rv-inclination', lesson: 'radial-velocity', step: 17 },
  { widget: 'astrometry-signature', lesson: 'radial-velocity', step: 24 },
  { widget: 'method-comparison', lesson: 'radial-velocity', step: 26 },
  { widget: 'planet-characterization', lesson: 'radial-velocity', step: 31 },
  { widget: 'hz-insolation', lesson: 'goldilocks-question', step: 2 },
  { widget: 'hz-spreading', lesson: 'goldilocks-question', step: 7 },
  { widget: 'hz-star', lesson: 'goldilocks-question', step: 10 },
  { widget: 'hz-boundaries', lesson: 'goldilocks-question', step: 18 },
  { widget: 'hz-orbit', lesson: 'goldilocks-question', step: 24 },
  { widget: 'hz-trappist', lesson: 'goldilocks-question', step: 30 },
  { widget: 'hz-candidates', lesson: 'goldilocks-question', step: 34 },
  { widget: 'dm-shapes', lesson: 'missing-mass', step: 2 },
  { widget: 'dm-enclosed', lesson: 'missing-mass', step: 6 },
  { widget: 'dm-fit', lesson: 'missing-mass', step: 13 },
  { widget: 'dm-flyby', lesson: 'missing-mass', step: 20 },
  { widget: 'dm-virial', lesson: 'missing-mass', step: 23 },
  { widget: 'dm-mond', lesson: 'missing-mass', step: 27 },
  { widget: 'dm-budget', lesson: 'missing-mass', step: 32 },
  { widget: 'tide-vectors', lesson: 'tides', step: 3 },
  { widget: 'tide-strength', lesson: 'tides', step: 10 },
  { widget: 'tide-compare', lesson: 'tides', step: 17 },
  { widget: 'tide-balance', lesson: 'tides', step: 21 },
  { widget: 'roche-model', lesson: 'tides', step: 23 },
  { widget: 'tide-disrupt', lesson: 'tides', step: 28 },
  { widget: 'chaos-divergence', lesson: 'butterfly-effect', step: 4 },
  { widget: 'resonance-periods', lesson: 'when-orbits-lock', step: 3 },
  { widget: 'resonance-conjunctions', lesson: 'when-orbits-lock', step: 8 },
  { widget: 'resonance-angle', lesson: 'when-orbits-lock', step: 12 },
  { widget: 'resonance-frame', lesson: 'when-orbits-lock', step: 27 },
  { widget: 'survey-schedule', lesson: 'detect-this-planet', step: 3 },
  { widget: 'transit-noise', lesson: 'detect-this-planet', step: 17 },
  { widget: 'gw-lab', lesson: 'what-is-a-gravitational-wave', step: 1 },
  { widget: 'gw-real', lesson: 'what-is-a-gravitational-wave', step: 25 },
  { widget: 'stellar-compare', lesson: 'a-universe-of-stars', step: 1 },
  { widget: 'stellar-lab', lesson: 'a-universe-of-stars', step: 3 },
  { widget: 'stellar-population', lesson: 'a-universe-of-stars', step: 25 },
  { widget: 'stellar-evolution', lesson: 'lives-of-stars', step: 2 },
];

/**
 * Record every piece of text the panels draw.
 *
 * Installed before the page's own scripts, so nothing is missed on the first
 * paint. `strokeText` is patched too: an outlined label is still a label.
 */
const RECORDER = () => {
  window.__labels = [];
  const proto = CanvasRenderingContext2D.prototype;
  // An animated panel repaints sixty times a second, and without this the
  // buffer holds sixty copies of every label - which then all "overlap" each
  // other. Every widget clears its canvas at the top of a frame, so a
  // clearRect that covers the whole surface is the frame boundary.
  const clear = proto.clearRect;
  proto.clearRect = function (x, y, w, h, ...rest) {
    if (
      this.canvas?.id === 'investigationToolCanvas' &&
      x <= 0 &&
      y <= 0 &&
      w >= this.canvas.clientWidth - 1
    ) {
      window.__labels = [];
    }
    return clear.call(this, x, y, w, h, ...rest);
  };
  for (const name of ['fillText', 'strokeText']) {
    const original = proto[name];
    proto[name] = function (text, x, y, ...rest) {
      try {
        const size = parseFloat(
          String(this.font).match(/(\d+(?:\.\d+)?)px/)?.[1] || '0'
        );
        const w = this.measureText(String(text)).width;
        const h = size * 1.05;
        // In the drawing context's own coordinates first, then through the
        // current transform. Half these panels write their y-axis title
        // rotated a quarter turn, and reading the untransformed x said the
        // label was a hundred pixels off the left edge when it is sitting
        // neatly in the margin.
        const x0 =
          this.textAlign === 'center'
            ? x - w / 2
            : this.textAlign === 'right' || this.textAlign === 'end'
              ? x - w
              : x;
        const y0 =
          this.textBaseline === 'top'
            ? y
            : this.textBaseline === 'middle'
              ? y - h / 2
              : y - h * 0.8;
        const m = this.getTransform();
        const at = (px, py) => ({
          x: m.a * px + m.c * py + m.e,
          y: m.b * px + m.d * py + m.f,
        });
        const corners = [
          at(x0, y0),
          at(x0 + w, y0),
          at(x0, y0 + h),
          at(x0 + w, y0 + h),
        ];
        const dpr = Math.min(window.devicePixelRatio || 1, 2);
        window.__labels.push({
          canvas: this.canvas?.id || '',
          text: String(text),
          size,
          x0: Math.min(...corners.map(c => c.x)) / dpr,
          x1: Math.max(...corners.map(c => c.x)) / dpr,
          y0: Math.min(...corners.map(c => c.y)) / dpr,
          y1: Math.max(...corners.map(c => c.y)) / dpr,
        });
      } catch {
        /* a measurement failure must not break the drawing */
      }
      return original.call(this, text, x, y, ...rest);
    };
  }
};

/**
 * The labels on the instrument canvas, as boxes in CSS pixels.
 *
 * The recorder has already resolved alignment, baseline, rotation and the
 * device-pixel scale, so what comes back here is where the text actually
 * landed on the picture the reader is looking at.
 */
async function labelsOn(page) {
  return page.evaluate(() => {
    const canvas = document.getElementById('investigationToolCanvas');
    const width = canvas?.clientWidth ?? 0;
    const height = canvas?.clientHeight ?? 0;
    const boxes = (window.__labels || []).filter(
      l => l.canvas === 'investigationToolCanvas' && l.text.trim()
    );
    return { width, height, boxes };
  });
}

/** Open the panel's step through the authoring preview and repaint it. */
async function openPanel(page, app, { lesson, step }) {
  await page.addInitScript(RECORDER);
  await app.boot({ url: `/?author=${lesson}&step=${step}` });
  await expect(page.locator('#investigationPanel')).toBeVisible();
  await expect(page.locator('#investigationToolCanvas')).toBeVisible();
  // A repaint with the recorder in place, and two frames for anything that
  // draws itself on a timer.
  await page.evaluate(() => {
    window.__labels = [];
    window.dispatchEvent(new Event('resize'));
  });
  await page.waitForTimeout(700);
}

test.describe('instrument labels are legible', () => {
  for (const panel of PANELS) {
    test(`${panel.widget}`, async ({ page, app }) => {
      await openPanel(page, app, panel);
      const { width, height, boxes } = await labelsOn(page);

      expect(boxes.length, 'the panel drew some text').toBeGreaterThan(0);

      // 1. Nothing below the shared floor. The floor is TYPE.MIN rather than
      // TYPE.TICK on purpose: thirteen widget families had settled on ten
      // pixels, and the brief was to get rid of the eight and nine pixel
      // labels, not to relay out fifty panels. New work uses TICK.
      const small = boxes
        .filter(b => b.size > 0 && b.size < TYPE.MIN)
        .map(b => `${b.size}px "${b.text.slice(0, 24)}"`);
      expect(small, 'labels below the shared floor').toEqual([]);

      // 2. Nothing drawn off the edge. A pixel of slack, because a centred
      // label on the last tick legitimately sits on the boundary.
      const off = boxes
        .filter(b => b.x0 < -1 || b.x1 > width + 1 || b.y1 > height + 1)
        .map(
          b =>
            `"${b.text.slice(0, 24)}" at ${Math.round(b.x0)},${Math.round(b.y0)}`
        );
      expect(off, `labels outside the ${width}x${height} canvas`).toEqual([]);

      // 3. No label on top of another. The tolerance is two pixels in each
      // direction: adjacent lines of a wrapped caption touch by a hair and
      // that is not what this is looking for.
      const hits = [];
      for (let i = 0; i < boxes.length; i++) {
        for (let j = i + 1; j < boxes.length; j++) {
          const a = boxes[i];
          const b = boxes[j];
          const dx = Math.min(a.x1, b.x1) - Math.max(a.x0, b.x0);
          const dy = Math.min(a.y1, b.y1) - Math.max(a.y0, b.y0);
          if (dx <= 2 || dy <= 2) continue;
          // Several panels draw a label twice - once in the background colour
          // as a halo and once in ink - so that it stays readable over a
          // filled shape. That is the technique working, not a collision.
          const sameText = a.text === b.text;
          const nearlyOnTopOfEachOther =
            Math.abs(a.x0 - b.x0) < 3 && Math.abs(a.y0 - b.y0) < 3;
          if (sameText && nearlyOnTopOfEachOther) continue;
          hits.push(`"${a.text.slice(0, 20)}" over "${b.text.slice(0, 20)}"`);
        }
      }
      expect(hits, 'labels drawn on top of each other').toEqual([]);
    });
  }
});
