#!/usr/bin/env node
// =============================================================================
// Build the user manual
// -----------------------------------------------------------------------------
// The manual is LaTeX in manual/, and the PDF at the repository root is a build
// artifact of it. Before this existed the PDF was the only copy: nobody could
// diff it, nobody could correct a sentence without the original .tex that had
// long since been lost, and it had drifted years behind the application it
// described.
//
//   npm run manual          regenerate the includes, compile, install the PDF
//   npm run manual:check    fail if the shipped PDF no longer matches the facts
//
// Three of the manual's files are generated and must not be hand-edited:
//
//   manual/facts.tex          the counts, as macros (tools/docs-facts.mjs)
//   manual/scenarios.tex      the scenario catalog, from js/data/scenarioInfo.js
//   manual/investigations.tex the lesson table, from the investigation manifest
//
// That is the whole point: a manual that claims a scenario count is a manual
// that will one day claim the wrong one, unless the claim is compiled from the
// catalog it describes.
//
// The engine is Tectonic, chosen because it is one binary with no TeX
// installation behind it and fetches only the packages the document asks for.
// =============================================================================

import { writeFile, readFile, mkdir, copyFile, rm } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { inflateSync } from 'node:zlib';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const MANUAL = join(REPO, 'manual');
const PDF = join(REPO, 'Gravitas_User_Manual.pdf');

// --- LaTeX escaping ----------------------------------------------------------

/**
 * Make a string from the application safe to typeset.
 *
 * Scenario summaries are written for a web page and contain characters LaTeX
 * reads as instructions. The Unicode replacements are the ones that actually
 * occur in the catalog - a solar-mass symbol and a non-breaking hyphen - and
 * are mapped rather than passed through because Latin Modern has no glyph for
 * the first and a reader should not meet a black box in a manual.
 *
 * @param {string} value - Text from the catalog or the manifest
 * @returns {string} The same text, as LaTeX
 */
export function tex(value) {
  return (
    String(value)
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/([&%$#_{}])/g, '\\$1')
      .replace(/~/g, '\\textasciitilde{}')
      .replace(/\^/g, '\\textasciicircum{}')
      .replace(/☉/g, '\\ensuremath{\\odot}')
      .replace(/‑/g, '-')
      // Straight quotes in the catalog are ASCII, and LaTeX renders a bare " and
      // a bare ' as *closing* quotes, so a quoted phrase comes out with two
      // right-hand marks around it. Pair them up instead. The apostrophe rule
      // needs a space or an opening bracket before the mark, so "a planet's
      // orbit" is left alone.
      .replace(/"([^"]*)"/g, "``$1''")
      .replace(/(^|[\s(])'([^']*)'/g, "$1`$2'")
  );
}

// --- generated includes ------------------------------------------------------

/** The scenario catalog, as a longtable grouped by concept tag. */
async function scenariosTex() {
  const { SCENARIO_INFO } = await import(
    new URL('../js/data/scenarioInfo.js', import.meta.url)
  );
  // Tag labels come from the message catalog, which is where the gallery gets
  // them, so a renamed concept renames itself here too.
  const { EN } = await import(new URL('../js/i18n/en.js', import.meta.url));
  const label = id =>
    EN[`tag.${id}.label`] ||
    id.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  const entries = Object.entries(SCENARIO_INFO);
  const byTag = new Map();
  for (const [name, info] of entries) {
    const primary = (info.tags || ['other'])[0];
    if (!byTag.has(primary)) byTag.set(primary, []);
    byTag.get(primary).push([name, info]);
  }

  const out = ['% Generated by tools/build-manual.mjs - do not edit.', ''];
  for (const [tag, rows] of [...byTag.entries()].sort()) {
    out.push(`\\subsection{${tex(label(tag))}}`);
    out.push('\\begin{description}[style=nextline,leftmargin=1em]');
    for (const [name, info] of rows) {
      out.push(
        `  \\item[${tex(info.title || name)}] ${tex(info.summary || '')}`
      );
    }
    out.push('\\end{description}');
    out.push('');
  }
  return out.join('\n');
}

/** The investigations, as a table plus a paragraph each. */
async function investigationsTex() {
  const { MANIFEST } = await import(
    new URL('../js/data/investigations/manifest.js', import.meta.url)
  );
  const out = [
    '% Generated by tools/build-manual.mjs - do not edit.',
    '',
    '\\begin{longtable}{@{}p{0.30\\linewidth}rrp{0.26\\linewidth}@{}}',
    '\\toprule',
    '\\textbf{Investigation} & \\textbf{Steps} & \\textbf{Graded} & \\textbf{Time} \\\\',
    '\\midrule',
    '\\endhead',
  ];
  for (const l of MANIFEST) {
    out.push(
      `${tex(l.title)} & ${l.stepCount} & ${l.gradedCount} & ${tex(l.duration)} \\\\`
    );
  }
  out.push('\\bottomrule', '\\end{longtable}', '');
  for (const l of MANIFEST) {
    out.push(`\\subsection{${tex(l.title)}}`);
    out.push(
      `\\emph{${tex(l.subtitle)}} \\quad ${l.stepCount} steps, ` +
        `${l.gradedCount} of them graded, ${tex(l.duration)}, ` +
        `${tex(l.level)}.`
    );
    out.push('');
    out.push(tex(l.summary));
    out.push('');
  }
  return out.join('\n');
}

// --- PDF inspection ----------------------------------------------------------

/**
 * Every stream in a PDF, inflated where it can be.
 *
 * A modern PDF keeps its page tree, its metadata and its outline inside
 * compressed object streams, so searching the raw bytes for `/Type /Page`
 * finds nothing at all. Scanning is done over a latin1 view, where one
 * character is one byte and string offsets are buffer offsets.
 */
function pdfBlobs(bytes) {
  const blobs = [bytes];
  const view = bytes.toString('latin1');
  const opener = /stream\r?\n/g;
  let m;
  while ((m = opener.exec(view)) !== null) {
    // "endstream" contains "stream"; skip the matches that are its tail.
    if (view.slice(Math.max(0, m.index - 3), m.index) === 'end') continue;
    const end = view.indexOf('endstream', m.index);
    if (end === -1) break;
    try {
      blobs.push(inflateSync(bytes.subarray(m.index + m[0].length, end)));
    } catch {
      /* not a deflate stream; its raw bytes are already in blobs[0] */
    }
    opener.lastIndex = end;
  }
  return Buffer.concat(blobs);
}

/**
 * What the shipped PDF says about itself.
 *
 * The facts are written into the document's keywords by the LaTeX source, so
 * checking that the PDF is current is reading one string rather than parsing
 * typeset text.
 *
 * @param {string} path - The PDF to inspect
 * @returns {{pages: number, keywords: object, lang: boolean, tagged: boolean,
 *   outline: boolean, links: Array<string>}} What it contains
 */
export function inspectPdf(path) {
  const bytes = readFileSync(path);
  const all = pdfBlobs(bytes);
  const text = all.toString('latin1');

  // hyperref writes its metadata as UTF-16BE hex strings when `unicode=true`,
  // and as literal strings otherwise. Read either.
  const pdfString = name => {
    const literal = text.match(new RegExp(`/${name}\\s*\\(([^)]*)\\)`));
    if (literal) return literal[1];
    const hex = text.match(new RegExp(`/${name}\\s*<([0-9A-Fa-f\\s]+)>`));
    if (!hex) return '';
    const bytes = Buffer.from(hex[1].replace(/\s+/g, ''), 'hex');
    return bytes.subarray(0, 2).toString('hex').toUpperCase() === 'FEFF'
      ? bytes.subarray(2).swap16().toString('utf16le')
      : bytes.toString('latin1');
  };

  const keywords = {};
  for (const pair of pdfString('Keywords').split(';')) {
    const [k, v] = pair.split('=').map(part => part && part.trim());
    if (k && v) keywords[k] = v;
  }

  return {
    pages: (text.match(/\/Type\s*\/Page[^s]/g) || []).length,
    keywords,
    lang: /\/Lang\s*[(<]/.test(text),
    toUnicode: text.includes('/ToUnicode'),
    tagged: text.includes('/StructTreeRoot'),
    outline: text.includes('/Outlines'),
    // The document title, not a bookmark's: both use /Title, and the outline's
    // entries come first in the file.
    title:
      [...text.matchAll(/\/Title\s*(?:\(([^)]*)\)|<([0-9A-Fa-f\s]+)>)/g)]
        .map(m =>
          m[1] !== undefined
            ? m[1]
            : (() => {
                const b = Buffer.from(m[2].replace(/\s+/g, ''), 'hex');
                return b.subarray(0, 2).toString('hex').toUpperCase() === 'FEFF'
                  ? b.subarray(2).swap16().toString('utf16le')
                  : b.toString('latin1');
              })()
        )
        .find(t => /Gravitas User Manual/.test(t)) || '',
    links: [
      ...new Set(
        [...text.matchAll(/\/URI\s*\(([^)]*)\)/g)].map(m => m[1].trim())
      ),
    ],
  };
}

// --- compiling ---------------------------------------------------------------

/** Regenerate every generated include. Returns whether anything changed. */
async function generateIncludes() {
  await mkdir(MANUAL, { recursive: true });
  const wanted = {
    'scenarios.tex': await scenariosTex(),
    'investigations.tex': await investigationsTex(),
  };
  let changed = [];
  for (const [name, body] of Object.entries(wanted)) {
    const path = join(MANUAL, name);
    const current = existsSync(path) ? await readFile(path, 'utf8') : '';
    if (current !== body) {
      await writeFile(path, body);
      changed.push(name);
    }
  }
  // facts.tex belongs to the documentation-facts tool; ask it to write.
  execFileSync('node', ['tools/docs-facts.mjs', '--sync'], {
    cwd: REPO,
    stdio: 'ignore',
  });
  return changed;
}

function compile() {
  const out = execFileSync(
    'tectonic',
    [
      '-X',
      'compile',
      'gravitas-user-manual.tex',
      '--keep-logs',
      '--outdir',
      '.',
    ],
    { cwd: MANUAL, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }
  );
  return out;
}

/** Overfull boxes are the usual way a LaTeX page goes wrong silently. */
function layoutProblems() {
  const log = join(MANUAL, 'gravitas-user-manual.log');
  if (!existsSync(log)) return [];
  const text = readFileSync(log, 'latin1');
  const overfull = [...text.matchAll(/Overfull \\hbox \((\d+(?:\.\d+)?)pt/g)]
    .map(m => Number(m[1]))
    // Under 5pt is invisible on the page; over it, something runs into the
    // margin and a reader can see it.
    .filter(pt => pt > 5);
  const undefined_ = [
    ...text.matchAll(/(LaTeX Warning: Reference[^\n]*)/g),
  ].map(m => m[1]);
  return [...overfull.map(pt => `overfull hbox by ${pt}pt`), ...undefined_];
}

async function main() {
  const check = process.argv.includes('--check');

  if (check) {
    const problems = [];
    if (!existsSync(PDF)) {
      problems.push('Gravitas_User_Manual.pdf is missing');
    } else {
      const { facts } = await (
        await import(new URL('./docs-facts.mjs', import.meta.url))
      ).gatherFacts({ full: false });
      const pdf = inspectPdf(PDF);
      const wanted = {
        scenarios: String(facts.scenarios),
        investigations: String(facts.investigations),
        steps: String(facts.investigationSteps),
        locales: String(facts.locales),
      };
      for (const [key, value] of Object.entries(wanted)) {
        if (pdf.keywords[key] !== value) {
          problems.push(
            `the shipped PDF says ${key}=${pdf.keywords[key] ?? '?'}, the source says ${value}`
          );
        }
      }
      if (!pdf.pages) problems.push('the shipped PDF has no pages');
      if (!pdf.lang) problems.push('the shipped PDF declares no language');
      if (!pdf.toUnicode) {
        problems.push(
          'the shipped PDF has no ToUnicode map: text will not extract'
        );
      }
      if (!pdf.outline) problems.push('the shipped PDF has no bookmarks');
    }
    if (problems.length) {
      for (const p of problems) process.stderr.write(`manual: ${p}\n`);
      process.stderr.write('\nRun `npm run manual`.\n');
      return 1;
    }
    process.stdout.write('The shipped user manual matches the application.\n');
    return 0;
  }

  const changed = await generateIncludes();
  if (changed.length) {
    process.stdout.write(`regenerated ${changed.join(', ')}\n`);
  }
  compile();
  const problems = layoutProblems();
  for (const p of problems) process.stderr.write(`layout: ${p}\n`);

  await copyFile(join(MANUAL, 'gravitas-user-manual.pdf'), PDF);
  for (const junk of ['gravitas-user-manual.pdf']) {
    await rm(join(MANUAL, junk), { force: true });
  }

  const pdf = inspectPdf(PDF);
  process.stdout.write(
    `Gravitas_User_Manual.pdf: ${pdf.pages} pages, ${pdf.links.length} external links, ` +
      `lang ${pdf.lang ? 'set' : 'MISSING'}, bookmarks ${pdf.outline ? 'yes' : 'NO'}, ` +
      `text extractable ${pdf.toUnicode ? 'yes' : 'NO'}, tagged ${pdf.tagged ? 'yes' : 'no'}\n`
  );
  return problems.length ? 1 : 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().then(code => process.exit(code));
}
