#!/usr/bin/env node
// =============================================================================
// Capability packages at build time
// -----------------------------------------------------------------------------
// Reads capabilities/*.json, validates them as a set, generates the compact
// catalog the runtime reads (js/platform/catalog.generated.js), and checks
// that what the manifests claim is true of the repository:
//
//   builtin references      every `builtin:<id>` is in js/platform/builtins.js
//   assets                  every declared file exists, and the service-worker
//                           precache has every offline asset under its policy
//   validation              every declared check is a registry entry, a jest
//                           suite or a browser spec that exists
//   licenses and citations  LICENSES.md names each license scope; NOTICE
//                           acknowledges each citation
//
//   node tools/capabilities.mjs check        the whole of the above
//   node tools/capabilities.mjs generate     rewrite the catalog
//   node tools/capabilities.mjs listing      a markdown table of the packages
// =============================================================================

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { PLATFORM_API, validatePackages } from '../js/platform/manifest.js';
import { BUILTIN_SOURCES } from '../js/platform/builtins.js';
import { precacheLists } from './build-service-worker.mjs';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIR = path.join(REPO, 'capabilities');
export const LISTING_FILE = path.join(REPO, 'docs', 'capabilities.md');
export const CATALOG_FILE = path.join(
  REPO,
  'js',
  'platform',
  'catalog.generated.js'
);

export function readPackages(dir = DIR) {
  return readdirSync(dir)
    .filter(f => f.endsWith('.json'))
    .sort()
    .map(f => ({
      file: f,
      manifest: JSON.parse(readFileSync(path.join(dir, f), 'utf8')),
    }));
}

/**
 * What the runtime needs of the manifests, as direct lookups and nothing else:
 * each package's version, API range and requirements, and each public id's
 * builtin entry. Titles, assets, licenses and validation are for the build and
 * the documentation, and never ship.
 */
export function runtimeCatalog(manifests) {
  const packages = {};
  const families = {};
  const lessons = {};
  const data = {};
  const migrations = {};
  const owners = {};
  for (const m of manifests) {
    if (m.migrations?.length) migrations[m.id] = m.migrations;
    packages[m.id] = [m.version, m.gravitas, m.requires || {}];
    for (const f of m.provides?.widgetFamilies || []) {
      families[f.id] = [f.entry, f.pick, f.widgets];
      owners[`widgetFamilies:${f.id}`] = m.id;
      for (const w of f.widgets) owners[`widgets:${w}`] = m.id;
    }
    for (const inv of m.provides?.investigations || []) {
      const translations = {};
      for (const t of m.provides?.translations || []) {
        if (t.investigation === inv.id) translations[t.locale] = t.entry;
      }
      lessons[inv.id] = [inv.entry, translations, m.id];
      owners[`investigations:${inv.id}`] = m.id;
    }
    for (const d of m.provides?.dataPacks || []) {
      data[d.id] = d.entry;
      owners[`dataPacks:${d.id}`] = m.id;
    }
  }
  return { packages, families, lessons, data, migrations, owners };
}

/** The catalog module, formatted as the repository formats it. */
export async function catalogSource(packages) {
  const c = runtimeCatalog(packages.map(p => p.manifest));
  const raw = [
    '// Generated by tools/capabilities.mjs from capabilities/*.json. Do not edit.',
    '',
    `export const PLATFORM_API = '${PLATFORM_API}';`,
    `export const PACKAGES = ${JSON.stringify(c.packages)};`,
    `export const FAMILIES = ${JSON.stringify(c.families)};`,
    `export const LESSONS = ${JSON.stringify(c.lessons)};`,
    `export const DATA = ${JSON.stringify(c.data)};`,
    `export const MIGRATIONS = ${JSON.stringify(c.migrations)};`,
    `export const OWNERS = ${JSON.stringify(c.owners)};`,
    '',
  ].join('\n');
  // Loaded here rather than at the top: under Jest the prettier package does
  // not load, and only `generate` needs it.
  const prettier = await import('prettier');
  const options = (await prettier.resolveConfig(CATALOG_FILE)) || {};
  return prettier.format(raw, { ...options, filepath: CATALOG_FILE });
}

/** Every repository-level problem with the packages, as strings. */
export async function checkRepository(packages) {
  const problems = [];
  const manifests = packages.map(p => p.manifest);
  for (const e of validatePackages(manifests))
    problems.push(`${e.package} ${e.path}: ${e.message}`);
  // Compared with the lists the generator produces, not by searching the file:
  // a path appears in the core list, the optional list or a locale's warm list,
  // and only the right one will do.
  const lists = await precacheLists();
  const warm = new Set([...lists.localeWarm.values()].flat());
  const listOf = p =>
    lists.core.includes(p)
      ? 'core'
      : lists.optional.includes(p)
        ? 'optional'
        : warm.has(p)
          ? 'locale'
          : 'none';
  const { CHECKS } = await import('./checks.mjs');
  const registry = new Set(CHECKS.map(c => c.id));
  const licenses = readFileSync(path.join(REPO, 'LICENSES.md'), 'utf8');
  const notice = readFileSync(path.join(REPO, 'NOTICE'), 'utf8');
  for (const m of manifests) {
    const walkRefs = v =>
      typeof v === 'string'
        ? v.startsWith('builtin:')
          ? [v]
          : []
        : Array.isArray(v)
          ? v.flatMap(walkRefs)
          : v && typeof v === 'object'
            ? Object.values(v).flatMap(walkRefs)
            : [];
    for (const ref of walkRefs(m.provides)) {
      const id = ref.slice('builtin:'.length);
      if (!BUILTIN_SOURCES[id])
        problems.push(`${m.id}: ${ref} is not in js/platform/builtins.js`);
      else if (!(m.assets || []).some(a => a.path === BUILTIN_SOURCES[id])) {
        problems.push(
          `${m.id}: ${ref} lives in ${BUILTIN_SOURCES[id]}, which the package does not declare as an asset`
        );
      }
    }
    for (const a of m.assets || []) {
      if (!existsSync(path.join(REPO, a.path)))
        problems.push(`${m.id}: asset ${a.path} does not exist`);
      const where = listOf(a.path);
      if (where !== a.offline) {
        problems.push(
          `${m.id}: ${a.path} is declared offline "${a.offline}" but the precache has it as "${where}"`
        );
      }
    }
    for (const v of m.validation || []) {
      const [kind, ref] = v.check.split(/:(.*)/s);
      const ok =
        kind === 'registry'
          ? registry.has(ref)
          : existsSync(path.join(REPO, ref));
      if (!ok) problems.push(`${m.id}: validation ${v.check} names no check`);
    }
    for (const l of m.licenses || []) {
      if (
        !licenses.includes(l.scope.replace('**', '**')) &&
        !licenses.includes(`\`${l.scope}\``)
      ) {
        const covered = l.license === 'MIT' || licenses.includes(l.scope);
        if (!covered)
          problems.push(`${m.id}: LICENSES.md does not name ${l.scope}`);
      }
    }
    for (const c of m.citations || []) {
      const who = /\(([^,]+),/.exec(c.text)?.[1] || c.text;
      if (!notice.includes(who.split(' ')[0]))
        problems.push(`${m.id}: NOTICE does not acknowledge ${c.text}`);
    }
  }
  // Compared as data, not text: the formatting is prettier's to check, and
  // what matters is that the runtime reads what the manifests say.
  const shipped = await import(
    `${pathToFileURL(CATALOG_FILE).href}?t=${Date.now()}`
  ).catch(() => null);
  const want = runtimeCatalog(manifests);
  const same =
    shipped &&
    shipped.PLATFORM_API === PLATFORM_API &&
    ['packages', 'families', 'lessons', 'data', 'migrations', 'owners'].every(
      k => JSON.stringify(shipped[k.toUpperCase()]) === JSON.stringify(want[k])
    );
  if (!same) {
    problems.push(
      'js/platform/catalog.generated.js is stale: run `node tools/capabilities.mjs generate`'
    );
  }
  return problems;
}

export function listing(packages) {
  const rows = packages.map(({ manifest: m }) => {
    const provides = Object.entries(m.provides || {})
      .map(([k, l]) => `${l.length} ${k}`)
      .join(', ');
    const licenses = (m.licenses || [])
      .map(l => `${l.license} (\`${l.scope}\`)`)
      .join('; ');
    const cites = (m.citations || []).map(c => c.text).join('; ') || '-';
    return `| \`${m.id}\` | ${m.version} | ${m.kind} | ${provides} | ${licenses} | ${cites} |`;
  });
  return [
    '| Package | Version | Kind | Provides | Licenses | Citations |',
    '|---|---|---|---|---|---|',
    ...rows,
  ].join('\n');
}

/** docs/capabilities.md: the installed packages, generated from them. */
export function listingFile(packages) {
  return [
    '# Capability packages',
    '',
    '<!-- Generated by `npm run capabilities` from capabilities/*.json. Do not edit. -->',
    '',
    'The capabilities that are described by a `gravitas.capability-package/1`',
    'manifest. Everything else is still built into the core; see',
    '[PLATFORM_PACKAGE_RFC.md](../PLATFORM_PACKAGE_RFC.md) and',
    '[CAPABILITY_RUNTIME.md](../CAPABILITY_RUNTIME.md).',
    '',
    listing(packages),
    '',
  ].join('\n');
}

async function main(argv) {
  const packages = readPackages();
  if (argv[0] === 'generate') {
    writeFileSync(CATALOG_FILE, await catalogSource(packages));
    writeFileSync(LISTING_FILE, listingFile(packages));
    console.log(
      `Wrote ${path.relative(REPO, CATALOG_FILE)}: ${packages.length} packages.`
    );
    return 0;
  }
  if (argv[0] === 'listing') {
    console.log(listing(packages));
    return 0;
  }
  const problems = await checkRepository(packages);
  if (problems.length) {
    for (const p of problems) console.error(`  ${p}`);
    return 1;
  }
  console.log(
    `${packages.length} capability packages valid, and true of the repository.`
  );
  return 0;
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main(process.argv.slice(2)).then(code => (process.exitCode = code));
}
