// =============================================================================
// Generated files and generated regions
// -----------------------------------------------------------------------------
// Three things that are derived rather than written, and so are produced here
// and checked for staleness by tools/docs-facts.mjs:
//
//   CITATION.cff        from tools/project-metadata.mjs plus the live counts
//   .zenodo.json        the same source, in Zenodo's shape
//   the model-by-investigation table in model/index.html
//
// The first two exist as a pair because Zenodo prefers .zenodo.json when both
// are present. A repository whose CFF is correct and whose Zenodo file is stale
// mints a DOI with the stale metadata, and nothing anywhere reports it.
//
// The third is a region inside a hand-written page rather than a whole file, so
// it is delimited by markers:
//
//     <!--fact-block:investigationModels-->  ... generated ...  <!--/fact-block-->
//
// Everything outside the markers is left exactly as it was.
// =============================================================================

import {
  AUTHORS,
  KEYWORDS,
  LICENSE,
  RELEASE,
  TITLE,
  URLS,
  abstractParagraphs,
} from './project-metadata.mjs';

/** Region markers, the block-level cousin of the inline fact marker. */
export const BLOCK_MARKER =
  /<!--fact-block:([a-zA-Z0-9_-]+)-->([\s\S]*?)<!--\/fact-block-->/g;

const escapeHtml = s =>
  String(s).replace(
    /[&<>"]/g,
    ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[ch]
  );

/** Fold a paragraph to a width, for the CFF's block scalar. */
function fold(text, width, indent) {
  const words = text.split(/\s+/);
  const lines = [];
  let line = '';
  for (const word of words) {
    if (line && (line + ' ' + word).length > width) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines.map(l => indent + l).join('\n');
}

/**
 * CITATION.cff.
 *
 * Hand-rendered rather than dumped by a YAML serialiser so that the file stays
 * readable and keeps its comments - a citation file is read by people at least
 * as often as by tools.
 *
 * @param {object} facts - From gatherFacts()
 * @returns {string} The file's contents
 */
export function citationCff(facts) {
  const lines = [
    '# Generated by tools/docs-facts.mjs from tools/project-metadata.mjs.',
    '# Do not edit by hand: run `npm run docs:sync`.',
    '#',
    '# The counts in the abstract come from the live catalogue, so they cannot',
    '# drift from the application the way a hand-written number does.',
    'cff-version: 1.2.0',
    `title: ${JSON.stringify(TITLE)}`,
    'message: "If you use Gravitas in teaching or research, please cite it."',
    'type: software',
    'authors:',
  ];

  for (const author of AUTHORS) {
    lines.push(`  - family-names: ${author.familyNames}`);
    lines.push(`    given-names: ${author.givenNames}`);
    if (author.affiliation) {
      lines.push(`    affiliation: ${author.affiliation}`);
    }
    if (author.email) lines.push(`    email: ${author.email}`);
    if (author.orcid) lines.push(`    orcid: ${JSON.stringify(author.orcid)}`);
  }

  lines.push(`repository-code: ${JSON.stringify(URLS.repository)}`);
  lines.push(`url: ${JSON.stringify(URLS.site)}`);
  lines.push('abstract: >-');
  lines.push(
    abstractParagraphs(facts)
      .map(p => fold(p, 72, '  '))
      .join('\n\n')
  );
  lines.push('keywords:');
  for (const keyword of KEYWORDS) lines.push(`  - ${keyword}`);
  lines.push(`license: ${LICENSE}`);

  // Release fields, or an explanation of their absence. CFF 1.2.0 makes both
  // optional, and an invented date is worse than a missing one.
  if (RELEASE.version)
    lines.push(`version: ${JSON.stringify(RELEASE.version)}`);
  if (RELEASE.dateReleased) {
    lines.push(`date-released: ${JSON.stringify(RELEASE.dateReleased)}`);
  }
  if (RELEASE.doi) {
    lines.push('identifiers:');
    lines.push('  - type: doi');
    lines.push(`    value: ${JSON.stringify(RELEASE.doi)}`);
    lines.push('    description: "The DOI of this version."');
  }
  if (!RELEASE.version || !RELEASE.dateReleased) {
    lines.push('');
    lines.push(
      '# No `version` or `date-released`: there is no Git tag and no GitHub'
    );
    lines.push(
      '# release yet, so either field would be invented. See RELEASING.md;'
    );
    lines.push(
      '# both are set in tools/project-metadata.mjs when a release is cut.'
    );
  }

  return lines.join('\n') + '\n';
}

/**
 * .zenodo.json.
 *
 * The same facts in Zenodo's vocabulary. `version` and `publication_date` are
 * omitted for the same reason they are omitted from the CFF; Zenodo fills the
 * publication date itself from the deposition when they are absent.
 *
 * @param {object} facts - From gatherFacts()
 * @returns {string} The file's contents
 */
export function zenodoJson(facts) {
  const description = abstractParagraphs(facts)
    .map(p => `<p>${escapeHtml(p)}</p>`)
    .join('');

  const record = {
    title: TITLE,
    description:
      description +
      `<p>Live at <a href="${URLS.site}">${URLS.site.replace(/^https:\/\//, '')}</a>.</p>`,
    upload_type: 'software',
    license: LICENSE.toLowerCase(),
    access_right: 'open',
    creators: AUTHORS.map(author => {
      const creator = {
        name: `${author.familyNames}, ${author.givenNames}`,
      };
      if (author.affiliation) creator.affiliation = author.affiliation;
      if (author.orcid) {
        creator.orcid = author.orcid.replace(/^https?:\/\/orcid\.org\//, '');
      }
      return creator;
    }),
    keywords: [...KEYWORDS],
    related_identifiers: [
      {
        identifier: URLS.site,
        relation: 'isSupplementTo',
        scheme: 'url',
      },
      {
        identifier: URLS.repository,
        relation: 'isSupplementTo',
        scheme: 'url',
      },
    ],
  };

  if (RELEASE.version) record.version = RELEASE.version;
  if (RELEASE.dateReleased) record.publication_date = RELEASE.dateReleased;

  return JSON.stringify(record, null, 2) + '\n';
}

/**
 * The model-by-investigation table, from the lessons themselves.
 *
 * The page said these notes "also appear in the instructor guide for each
 * lesson", and they do - `modelNotes` in js/data/instructorContent.js is where
 * the guide gets them. The table was a hand-copied subset of six of the twelve,
 * so half the lessons had no row at all and the claim was only half true.
 * Generated from the same field, it is true by construction and complete by
 * construction.
 *
 * @param {object} deps - {manifest, instructor}
 * @returns {string} HTML rows for the table body
 */
export function investigationModelRows({ manifest, instructor }) {
  const rows = [];
  for (const lesson of manifest) {
    const notes = instructor[lesson.id]?.modelNotes;
    if (!notes) {
      // Reported by the checker rather than papered over with an empty cell.
      rows.push(
        `            <tr>\n              <td>${escapeHtml(lesson.title)}</td>\n` +
          `              <td><em>No model notes recorded for this lesson.</em></td>\n            </tr>`
      );
      continue;
    }
    const prose = escapeHtml(notes.replace(/\s+/g, ' ').trim());
    rows.push(
      `            <tr>\n              <td>${escapeHtml(lesson.title)}</td>\n` +
        `              <td>${prose}</td>\n            </tr>`
    );
  }
  return rows.join('\n');
}

/**
 * Every generated region, by marker name.
 *
 * @param {object} deps - {facts, manifest, instructor}
 * @returns {Object<string, string>} Marker name -> replacement text
 */
export function generatedBlocks({ manifest, instructor }) {
  return {
    investigationModels: `\n${investigationModelRows({ manifest, instructor })}\n          `,
  };
}
