// =============================================================================
// Generated files and generated regions
// -----------------------------------------------------------------------------
// Three things that are derived rather than written, and so are produced here
// and checked for staleness by tools/docs-facts.mjs:
//
//   CITATION.cff        from tools/project-metadata.mjs plus the live counts
//   .zenodo.json        the same source, in Zenodo's shape
//   the model-by-investigation table in model/index.html
//
// The first two exist as a pair because Zenodo prefers .zenodo.json when both
// are present. A repository whose CFF is correct and whose Zenodo file is stale
// mints a DOI with the stale metadata, and nothing anywhere reports it.
//
// The third is a region inside a hand-written page rather than a whole file, so
// it is delimited by markers:
//
//     <!--fact-block:investigationModels-->  ... generated ...  <!--/fact-block-->
//
// Everything outside the markers is left exactly as it was.
// =============================================================================

import {
  ACKNOWLEDGMENT,
  AUTHORS,
  KEYWORDS,
  LICENSE,
  CONTENT_LICENSE,
  LICENSE_NOTE,
  RELEASE,
  TITLE,
  URLS,
  abstractParagraphs,
  PAPER,
} from './project-metadata.mjs';
import { describeKinds } from '../js/physicsKinds.js';

/** Region markers, the block-level cousin of the inline fact marker. */
export const BLOCK_MARKER =
  /<!--fact-block:([a-zA-Z0-9_-]+)-->([\s\S]*?)<!--\/fact-block-->/g;

const escapeHtml = s =>
  String(s).replace(
    /[&<>"]/g,
    ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[ch]
  );

/** Fold a paragraph to a width, for the CFF's block scalar. */
function fold(text, width, indent) {
  const words = text.split(/\s+/);
  const lines = [];
  let line = '';
  for (const word of words) {
    if (line && (line + ' ' + word).length > width) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines.map(l => indent + l).join('\n');
}

/**
 * CITATION.cff.
 *
 * Hand-rendered rather than dumped by a YAML serializer so that the file stays
 * readable and keeps its comments - a citation file is read by people at least
 * as often as by tools.
 *
 * @param {object} facts - From gatherFacts()
 * @returns {string} The file's contents
 */
export function citationCff(facts) {
  const lines = [
    '# Generated by tools/docs-facts.mjs from tools/project-metadata.mjs.',
    '# Do not edit by hand: run `npm run docs:sync`.',
    '#',
    '# The counts in the abstract come from the live catalog, so they cannot',
    '# drift from the application the way a hand-written number does.',
    'cff-version: 1.2.0',
    `title: ${JSON.stringify(TITLE)}`,
    'message: "If you use Gravitas in teaching or research, please cite it."',
    'type: software',
    'authors:',
  ];

  for (const author of AUTHORS) {
    lines.push(`  - family-names: ${author.familyNames}`);
    lines.push(`    given-names: ${author.givenNames}`);
    if (author.affiliation) {
      // Quoted: the affiliation is a full departmental address and carries
      // commas, and a plain YAML scalar is a poor place to find out whether
      // that parses the way it reads.
      lines.push(`    affiliation: ${JSON.stringify(author.affiliation)}`);
    }
    if (author.email) lines.push(`    email: ${author.email}`);
    if (author.orcid) lines.push(`    orcid: ${JSON.stringify(author.orcid)}`);
  }

  lines.push(`repository-code: ${JSON.stringify(URLS.repository)}`);
  lines.push(`url: ${JSON.stringify(URLS.site)}`);
  lines.push('abstract: >-');
  lines.push(
    abstractParagraphs(facts)
      .map(p => fold(p, 72, '  '))
      .join('\n\n')
  );
  lines.push('keywords:');
  for (const keyword of KEYWORDS) lines.push(`  - ${keyword}`);
  // Both, because they cover different files. CFF 1.2.0 allows a list of SPDX
  // identifiers here, and the code license is first - which is the one
  // .zenodo.json carries, and what tools/validate-citation.mjs compares.
  lines.push('license:');
  for (const id of [LICENSE, CONTENT_LICENSE]) lines.push(`  - ${id}`);

  // Release fields, or an explanation of their absence. CFF 1.2.0 makes both
  // optional, and an invented date is worse than a missing one.
  if (RELEASE.version)
    lines.push(`version: ${JSON.stringify(RELEASE.version)}`);
  if (RELEASE.dateReleased) {
    lines.push(`date-released: ${JSON.stringify(RELEASE.dateReleased)}`);
  }
  if (RELEASE.doi) {
    lines.push('identifiers:');
    lines.push('  - type: doi');
    lines.push(`    value: ${JSON.stringify(RELEASE.doi)}`);
    lines.push('    description: "The DOI of this version."');
  }
  if (!RELEASE.version || !RELEASE.dateReleased) {
    lines.push('');
    lines.push(
      '# No `version` or `date-released`: there is no Git tag and no GitHub'
    );
    lines.push(
      '# release yet, so either field would be invented. See RELEASING.md;'
    );
    lines.push(
      '# both are set in tools/project-metadata.mjs when a release is cut.'
    );
  }

  return lines.join('\n') + '\n';
}

/**
 * .zenodo.json.
 *
 * The same facts in Zenodo's vocabulary. `version` and `publication_date` are
 * omitted for the same reason they are omitted from the CFF; Zenodo fills the
 * publication date itself from the deposition when they are absent.
 *
 * @param {object} facts - From gatherFacts()
 * @returns {string} The file's contents
 */
export function zenodoJson(facts) {
  const description = abstractParagraphs(facts)
    .map(p => `<p>${escapeHtml(p)}</p>`)
    .join('');

  const record = {
    title: TITLE,
    description:
      description +
      `<p>Live at <a href="${URLS.site}">${URLS.site.replace(/^https:\/\//, '')}</a>.</p>`,
    upload_type: 'software',
    license: LICENSE.toLowerCase(),
    access_right: 'open',
    creators: AUTHORS.map(author => {
      const creator = {
        name: `${author.familyNames}, ${author.givenNames}`,
      };
      if (author.affiliation) creator.affiliation = author.affiliation;
      if (author.orcid) {
        creator.orcid = author.orcid.replace(/^https?:\/\/orcid\.org\//, '');
      }
      return creator;
    }),
    keywords: [...KEYWORDS],
    // Zenodo's own field for exactly this. Prose rather than a structured
    // grant, because there is no award number to put in one.
    notes: `${ACKNOWLEDGMENT}\n\n${LICENSE_NOTE}`,
    related_identifiers: [
      {
        identifier: URLS.site,
        relation: 'isSupplementTo',
        scheme: 'url',
      },
      {
        identifier: URLS.repository,
        relation: 'isSupplementTo',
        scheme: 'url',
      },
      // The paper, as `isDescribedBy`: the deposit is the software and the
      // paper describes it, which is the direction Zenodo's vocabulary means.
      // Recorded by arXiv id rather than DOI while the DataCite DOI is not yet
      // registered - see PAPER in tools/project-metadata.mjs. This reaches a
      // Zenodo record only on the next deposit; it cannot change one already
      // archived.
      ...(PAPER.doi
        ? [{ identifier: PAPER.doi, relation: 'isDescribedBy', scheme: 'doi' }]
        : PAPER.arxivId
          ? [
              {
                identifier: `arXiv:${PAPER.arxivId}`,
                relation: 'isDescribedBy',
                scheme: 'arxiv',
              },
            ]
          : []),
    ],
  };

  if (RELEASE.version) record.version = RELEASE.version;
  if (RELEASE.dateReleased) record.publication_date = RELEASE.dateReleased;

  return JSON.stringify(record, null, 2) + '\n';
}

/**
 * The model-by-investigation table, from the lessons themselves.
 *
 * The page said these notes "also appear in the instructor guide for each
 * lesson", and they do - `modelNotes` in js/data/instructorContent.js is where
 * the guide gets them. The table was a hand-copied subset of six of the twelve,
 * so half the lessons had no row at all and the claim was only half true.
 * Generated from the same field, it is true by construction and complete by
 * construction.
 *
 * @param {object} deps - {manifest, instructor}
 * @returns {string} HTML rows for the table body
 */
export function investigationModelRows({ manifest, instructor }) {
  const rows = [];
  for (const lesson of manifest) {
    const notes = instructor[lesson.id]?.modelNotes;
    if (!notes) {
      // Reported by the checker rather than papered over with an empty cell.
      rows.push(
        `            <tr>\n              <td>${escapeHtml(lesson.title)}</td>\n` +
          `              <td><em>No model notes recorded for this lesson.</em></td>\n            </tr>`
      );
      continue;
    }
    const prose = escapeHtml(notes.replace(/\s+/g, ' ').trim());
    rows.push(
      `            <tr>\n              <td>${escapeHtml(lesson.title)}</td>\n` +
        `              <td>${prose}</td>\n            </tr>`
    );
  }
  return rows.join('\n');
}

/**
 * Every generated region, by marker name.
 *
 * @param {object} deps - {facts, manifest, instructor}
 * @returns {Object<string, string>} Marker name -> replacement text
 */
/**
 * The physics suite's coverage table, from the suite itself.
 *
 * This was a hand-maintained table. It said 162 checks in four categories
 * while the suite ran 243 in five, and the document contradicted itself forty
 * lines apart - the sentence above the table carried a generated number and
 * was right, the table was written by hand and was not. Generating it is the
 * only version of this that stays true.
 *
 * @param {{total: number, groups: Array, byKind: object}} inventory - Counted
 *   from a `validate-physics --json` run
 * @returns {string} The markdown table, between its markers
 */
function physicsCoverageTable(inventory) {
  const rows = inventory.groups.map(
    g => `| ${g.group} | ${g.checks} | ${describeKinds(g.kinds)} |`
  );
  const total =
    `| **Total** | **${inventory.total}** | ` +
    `${describeKinds(inventory.byKind)} |`;
  return [
    '',
    '| Area | Checks | Kinds |',
    '| --- | --- | --- |',
    ...rows,
    total,
    '',
  ].join('\n');
}

/**
 * The Zenodo badge, and the citation with both identifiers.
 *
 * A generated block rather than `<!--fact:-->` markers, and the reason is
 * worth writing down. A fact marker is an HTML comment, which a markdown
 * renderer strips from prose - but not from inside a link destination. Put one
 * in a URL and GitHub percent-encodes it into the href, producing
 * `https://doi.org/%3C!--fact:doi--%3E10.5281/...` - a dead badge and a dead
 * link that still look right in the source file. A block wraps whole lines
 * from outside, so the URLs inside it are ordinary text.
 *
 * @returns {string} Markdown, or a note when there is no DOI yet
 */
function citationBlock() {
  if (!RELEASE.doi) {
    return '\nNot archived yet: there is no release, so there is no DOI. See\n[RELEASING.md](RELEASING.md).\n';
  }
  const v = RELEASE.doi;
  const c = RELEASE.conceptDoi;
  const lines = [
    '',
    `> Ziegler, C. (${(RELEASE.dateReleased || '').slice(0, 4)}). *${TITLE}*`,
    `> (Version ${RELEASE.version}) [Computer software]. Zenodo.`,
    `> <https://doi.org/${v}>`,
    '',
    '| | |',
    '| --- | --- |',
    `| **This version (${RELEASE.version})** | [${v}](https://doi.org/${v}) |`,
  ];
  if (c) {
    lines.push(`| **All versions** | [${c}](https://doi.org/${c}) |`);
  }
  if (PAPER.url) {
    // After the software identifiers, not before them: the paper itself asks
    // readers to cite the versioned archive, so leading with the paper here
    // would contradict the thing it points at.
    const cite = PAPER.doi
      ? `<https://doi.org/${PAPER.doi}>`
      : `arXiv:${PAPER.arxivId}, <${PAPER.url}>`;
    lines.push('');
    lines.push(`The paper describing Gravitas is *${PAPER.title}*`);
    lines.push(
      `(${cite}). Cite the software above for what your students ran,`
    );
    lines.push('and the paper for the design it describes.');
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * The Zenodo DOI badge. Uses the concept DOI so it follows the newest release;
 * falls back to the version DOI if there is somehow no concept DOI.
 *
 * @returns {string} Markdown, or empty when there is nothing to point at
 */
function doiBadgeBlock() {
  const d = RELEASE.conceptDoi || RELEASE.doi;
  if (!d) return '\n';
  // Own lines, both ends. A line that begins with an HTML comment is raw HTML
  // to a markdown renderer, and the image syntax after it is never parsed -
  // the badge comes out as literal `[![DOI](` text next to an autolink.
  return `\n[![DOI](https://zenodo.org/badge/DOI/${d}.svg)](https://doi.org/${d})\n`;
}

export function generatedBlocks({ manifest, instructor, physics = null }) {
  return {
    doiBadge: doiBadgeBlock(),
    citation: citationBlock(),
    investigationModels: `\n${investigationModelRows({ manifest, instructor })}\n          `,
    // Only a run of the suite can produce this, so a cheap docs check leaves
    // the block alone rather than claiming nobody generates it.
    ...(physics ? { physicsCoverage: physicsCoverageTable(physics) } : {}),
  };
}
