// =============================================================================
// A synthetic observation, and the truth that made it
// -----------------------------------------------------------------------------
// Every forward model returns a gravitas.observation with origin 'synthetic'
// and a `synthetic` block that holds what an instrument never tells you: the
// model, the setup, the seed and the truth manifest (the parameters that made
// the numbers, and what noise was injected). The Observatory, the inference core,
// the measurement pipeline and the analysis lab read the observation like any
// other; the truth manifest is only for "compare with truth".
//
//   synthetic: {
//     forwardModel: { id, version },
//     setup:        gravitas.observing-setup/1 as run,
//     truth: {
//       parameters: [{ id, name, value, unit, fit? }],   `fit` is the name the
//                    inference core's model gives it, when it has one
//       injected:   { whiteSigma, redSigma, offset, trend, outlierRows },
//       columns?:   { name: [values] }                    per-row truth
//       notes:      [text]                                what the model leaves out
//     },
//   }
//
// Pure: no DOM.
// =============================================================================

import { FORMAT, FORMAT_VERSION } from '../observatory/schema.js';

export const SYNTHETIC_CREDIT =
  'Gravitas forward model: synthetic, not observed';
export const SYNTHETIC_LICENSE = Object.freeze({
  status: 'generated',
  statement:
    'Generated by Gravitas from a stated model, setup and seed; it contains no third-party data.',
});

/** Whether an observation was made by a forward model. */
export const isSynthetic = o => o?.origin === 'synthetic';

/**
 * Assemble the observation a forward model returns.
 *
 * @param {object} p
 * @param {string} p.model - Forward model id
 * @param {string} p.version
 * @param {object} p.setup - As run (normalized)
 * @param {string} p.kind - 'time-series' | 'spectrum' | 'image' | 'table'
 * @param {string} p.title
 * @param {Array<object>} p.columns - Observation columns
 * @param {object} p.axes
 * @param {object} p.truth - { parameters, injected, columns?, notes }
 * @param {object} [p.extra] - time, spectral, image, object
 */
export function syntheticObservation(p) {
  const { setup } = p;
  return {
    format: FORMAT,
    formatVersion: FORMAT_VERSION,
    kind: p.kind,
    id: `synthetic:${p.model}:${setup.seed}`,
    title: p.title,
    object: p.extra?.object ?? null,
    facility: 'Gravitas forward model (synthetic)',
    origin: 'synthetic',
    source: { kind: 'forward', id: p.model, version: p.version },
    credit: SYNTHETIC_CREDIT,
    license: { ...SYNTHETIC_LICENSE },
    citations: [],
    reductions: [`Synthetic: ${p.model} forward model, seed "${setup.seed}".`],
    columns: p.columns,
    axes: p.axes,
    ...(p.extra?.time ? { time: p.extra.time } : {}),
    ...(p.extra?.spectral ? { spectral: p.extra.spectral } : {}),
    ...(p.extra?.image ? { image: p.extra.image } : {}),
    masks: [],
    annotations: [],
    synthetic: {
      forwardModel: { id: p.model, version: p.version },
      setup,
      truth: p.truth,
    },
  };
}

/** The columns of a value with its stated uncertainty, when there is one. */
export function valueColumns(id, name, unit, values, sigma) {
  const cols = [{ id, name, unit, role: 'value', values }];
  if (sigma)
    cols.push({
      id: `${id}-sigma`,
      name: `${name}, uncertainty`,
      unit,
      role: 'uncertainty',
      of: id,
      values: sigma,
    });
  return cols;
}

/**
 * What a fit recovered, set beside what made the data.
 *
 * Reads the truth manifest and a gravitas.inference result's fit (its
 * `parameters` with `name`, `value`, `sigma`, and optionally the profile
 * intervals) and returns one row per truth parameter the fit also estimated.
 * `pull` is (recovered - truth) / sigma; `within` is whether the truth lies
 * inside the recovered one-sigma interval, and `within2` two sigma. A fit that
 * did not estimate a parameter has no row; the manifest's parameters that the
 * fit never saw are returned in `unfitted`.
 *
 * @param {object} observation - Synthetic
 * @param {{parameters: Array<{name, value, sigma}>, derived?: Array}} fit
 * @returns {{rows: Array<object>, unfitted: Array<object>}|null} null when the
 *   observation is not synthetic
 */
export function compareWithTruth(observation, fit) {
  const truth = observation?.synthetic?.truth;
  if (!truth || !fit) return null;
  const found = [...(fit.parameters ?? []), ...(fit.derived ?? [])];
  const rows = [];
  const unfitted = [];
  for (const t of truth.parameters) {
    const name = t.fit ?? t.id;
    const r = found.find(p => p.name === name);
    if (!r || !Number.isFinite(r.value)) {
      unfitted.push(t);
      continue;
    }
    const sigma = Number.isFinite(r.sigma) && r.sigma > 0 ? r.sigma : null;
    const pull = sigma ? (r.value - t.value) / sigma : null;
    rows.push({
      id: t.id,
      name: t.name,
      unit: t.unit,
      truth: t.value,
      recovered: r.value,
      sigma,
      difference: r.value - t.value,
      pull,
      within: pull === null ? null : Math.abs(pull) <= 1,
      within2: pull === null ? null : Math.abs(pull) <= 2,
    });
  }
  return { rows, unfitted };
}

/**
 * Grade an answer to "what would this survey have seen" against the truth
 * manifest: the answer is right when it is within `tolerance` (a fraction of
 * the truth, or absolute when the truth is 0) of the named truth parameter.
 * @returns {{ok: boolean, truth: number, difference: number}|null} null when the
 *   observation is not synthetic or has no such parameter
 */
export function gradeAgainstTruth(observation, id, answer, tolerance) {
  const p = observation?.synthetic?.truth?.parameters?.find(q => q.id === id);
  if (!p || !Number.isFinite(answer)) return null;
  const difference = answer - p.value;
  const scale = p.value === 0 ? 1 : Math.abs(p.value);
  return {
    ok: Math.abs(difference) / scale <= tolerance,
    truth: p.value,
    difference,
  };
}
